#!/usr/bin/env Rscript
# ============================================================================
# Script:       fit.roc.glm.em.R
# Version:      0.7.0
# Created:      2026-06-17
# Revised:      2026-06-19
# Purpose:      Fit the ROC codon model as a multinomial GLMM by coordinate
#               ascent (IRLS-EM) -- a fast, deterministic alternative to native
#               MCMC. CSP step = per-AA multinomial logistic GLM (codon ~ phi);
#               phi step = per-gene analytic damped Fisher-scoring (the NB /
#               Poisson-Gamma update) + a median-gauged Gamma(sphi) prior (the
#               prior pins the scale, so no separate gauge step). Laplace SEs for
#               phi/dM/dEta. sphi (= SD log phi) is weakly identified from codon
#               data; --est-sphi profiles a proper ADAPTIVE GAUSS-HERMITE
#               marginal (integrates each gene's phi out; the single-point
#               Laplace marginal is artifactual and monotone -- both are reported
#               for comparison, plus the data-fit plateau cross-check). Default
#               is fixed --sphi. See notes/sphi-Ne-metrics-gamma-theory.md.
#
#               ROC log-odds linearity:  log P(codon c | gene g)/P(ref) =
#               dM_c + dEta_c * phi_g  -> given phi it is a multinomial GLM,
#               given the GLM it is a per-gene 1-D solve.
#
# Usage:        Rscript fit.roc.glm.em.R [--lib DIR] [--fasta F] [--deta CSV]
#                                [--phi-ref CSV] [--sphi N] [--est-sphi T/F] [--png F]
#                                [--verbose T/F] [--dry-run] [--help]
#               Defaults point at the S288c proof-of-concept data that lives in the
#               Analyses-RibModelFramework repo (roc/s.cerevisiae); override via flags.
#
# Provenance:   Promoted from Analyses-RibModelFramework roc/scripts/ @ 0476b94
#               (2026-06-19); see that repo's roc/notes/ for the exploratory history.
#
# Options:
#   --dry-run   Resolve + validate config and input files, then exit (no fit)
#   --verbose   Print the per-iteration convergence trace (default TRUE)
#   --help      Print this usage block and exit
#
# Output:       stdout: convergence trace + validation (phi vs native ROC fit,
#                       dEta/dM vs published); PNG diagnostic.
#
# Session:      ROC sphi/Ne/metrics theory -> GLM-EM prototype
# AI Model:     Claude Opus 4.8
# Attribution:  Generated by Michael Gilchrist in collaboration with Claude Opus 4.8
# ============================================================================

args <- commandArgs(TRUE)
usage <- function(){
  cat("Usage: Rscript fit.roc.glm.em.R [--lib DIR] [--fasta F] [--deta CSV] [--dM CSV]\n",
      "          [--phi-ref CSV] [--sphi N] [--est-sphi T/F] [--png F]\n",
      "          [--verbose T/F] [--dry-run] [--help]\n",
      "Fits the ROC codon model as a multinomial GLMM by coordinate ascent.\n",
      "Defaults point at the S288c proof-of-concept data; see the script header.\n", sep="")
}
has.flag <- function(flag) flag %in% args
## getarg: supports '--flag value' and '--flag=value'; returns def if the flag is
## absent OR its value is missing (last token, or the next token is another flag).
getarg <- function(flag, def){
  eqi <- grep(paste0("^", flag, "="), args, fixed=FALSE)
  if (length(eqi)) return(sub(paste0("^", flag, "="), "", args[eqi[1]]))
  i <- match(flag, args)
  if (is.na(i) || i+1 > length(args) || grepl("^--", args[i+1])) return(def)
  args[[i+1]]
}
parse_logical <- function(flag, def){
  v <- getarg(flag, def); lv <- tolower(as.character(v))
  if (lv %in% c("t","true","1","yes","y"))  return(TRUE)
  if (lv %in% c("f","false","0","no","n")) return(FALSE)
  stop(sprintf("%s expects a logical (T/F/TRUE/FALSE/1/0/yes/no); got '%s'", flag, v), call.=FALSE)
}
parse_num <- function(flag, def){
  v <- getarg(flag, def); n <- suppressWarnings(as.numeric(v))
  if (is.na(n)) stop(sprintf("%s expects a number; got '%s'", flag, v), call.=FALSE)
  n
}
if (has.flag("--help") || has.flag("-h")) { usage(); quit(save="no", status=0) }

SC      <- "/home/mikeg/Repositories/Analyses-RibModelFramework/roc/s.cerevisiae"
lib     <- getarg("--lib", "~/R/lib/main-a664454")
fasta   <- getarg("--fasta",  file.path(SC,"adapter.dev/Input/FASTA/Real/S288c_1000.fasta"))
deta.f  <- getarg("--deta",   file.path(SC,"results/fit-01/parameter.estimates/Sc_sampled_1000.genes_index-1_deta.csv"))
dM.f    <- getarg("--dM",     file.path(SC,"results/fit-01/parameter.estimates/Sc_sampled_1000.genes_index-1_dM.csv"))
phi.ref <- getarg("--phi-ref",file.path(SC,"adapter.dev/priors/phi_native_S288c_dual_LN_mixture_posterior_medians.csv"))
sphi.fix <- parse_num("--sphi", "1.0")
est.sphi <- parse_logical("--est-sphi", "FALSE")   # jointly estimate sphi?
verbose  <- parse_logical("--verbose", "TRUE")     # per-iteration convergence trace
dry.run  <- has.flag("--dry-run")
png.out <- getarg("--png", "/tmp/roc_glm_em_poc.png")

## --- validate input files up front (clear error, not a cryptic read failure) ---
in.files <- c(fasta=fasta, deta=deta.f, dM=dM.f, "phi-ref"=phi.ref)
miss <- in.files[!file.exists(path.expand(in.files))]
if (length(miss)) stop(sprintf("missing input file(s):\n%s",
    paste(sprintf("  --%s : %s", names(miss), miss), collapse="\n")), call.=FALSE)
if (dry.run){
  cat("DRY RUN -- config resolved, all input files present:\n")
  cat(sprintf("  lib=%s\n  sphi.fix=%g  est.sphi=%s  verbose=%s\n  png=%s\n",
              lib, sphi.fix, est.sphi, verbose, png.out))
  for (nm in names(in.files)) cat(sprintf("  %-8s %s\n", nm, in.files[nm]))
  quit(save="no", status=0)
}

.libPaths(c(path.expand(lib), .libPaths()))
suppressPackageStartupMessages(library(VGAM))

inv_trigamma <- function(t) uniroot(function(k) trigamma(k)-t, c(1e-3,1e6))$root

## Gauss-Hermite nodes/weights for the physicists' weight exp(-x^2), via the
## Golub-Welsch algorithm (eigendecomposition of the symmetric tridiagonal
## Jacobi matrix). Pure base R, no external quadrature package needed.
gh_nodes <- function(n){
  if (n==1) return(list(x=0, w=sqrt(pi)))
  j <- 1:(n-1); b <- sqrt(j/2)
  J <- matrix(0, n, n); J[cbind(j,j+1)] <- b; J[cbind(j+1,j)] <- b
  e <- eigen(J, symmetric=TRUE); o <- order(e$values)
  list(x=e$values[o], w=(sqrt(pi)*e$vectors[1,]^2)[o])
}
GHN <- gh_nodes(20)

## --- AA groups + reference codon, taken FROM the published dEta CSV so the
##     grouping/reference convention matches AnaCoDa exactly. ---
det <- read.csv(deta.f); dMt <- read.csv(dM.f)
aa.list <- split(det, det$AA)                       # AA -> data.frame(Codon, Mean,...)
aa.list <- aa.list[vapply(aa.list, nrow, 1L) >= 2]  # degenerate AAs only
AAs <- names(aa.list)
# reference codon per AA = the one with published Mean exactly 0 (AnaCoDa pins it)
ref.codon <- vapply(aa.list, function(d){ r <- d$Codon[abs(d$Mean) < 1e-12]; if(length(r)) r[1] else tail(d$Codon,1) }, "")
codons.by.aa <- lapply(aa.list, function(d) d$Codon)
all.codons <- unlist(codons.by.aa, use.names=FALSE)
cat(sprintf("AAs: %d   sense codons modelled: %d\n", length(AAs), length(all.codons)))

## --- read FASTA, count codons per gene ---
ln <- readLines(fasta, warn=FALSE); h <- grepl("^>", ln)
gid <- sub("^>([^ ]+).*","\\1", ln[h]); grp <- cumsum(h)
seqs <- toupper(tapply(ln[!h], grp[!h], paste0, collapse="")); seqs <- setNames(unname(seqs), gid)
G <- length(seqs); cat("genes:", G, "\n")
ccount <- function(s){ n<-nchar(s); if(n<3) return(setNames(integer(length(all.codons)),all.codons))
  table(factor(substring(s,seq(1,n-2,3),seq(3,n,3)), levels=all.codons)) }
CC <- t(vapply(seqs, ccount, integer(length(all.codons)))); colnames(CC) <- all.codons

## --- init phi: PC1 of the 2-fold focal fractions (robust mode anchor) ---
two <- AAs[vapply(codons.by.aa[AAs], length, 1L)==2]
Fr <- sapply(two, function(a){ cs<-codons.by.aa[[a]]; f<-CC[,cs[1]]/(CC[,cs[1]]+CC[,cs[2]]); f })
Fr[!is.finite(Fr)] <- NA; cm<-colMeans(Fr,na.rm=TRUE); for(j in seq_len(ncol(Fr))) Fr[is.na(Fr[,j]),j]<-cm[j]
pc <- prcomp(scale(Fr,center=TRUE,scale=FALSE))$x[,1]
if (cor(pc, rowMeans(abs(sweep(Fr,2,cm)))) < 0) pc <- -pc
phi <- setNames(exp((pc-median(pc))/sd(pc)), gid); phi <- phi/median(phi)

## --- median-gauged Gamma prior; sphi (= SD log phi) fixed at --sphi unless
##     --est-sphi (then profiled, taking the data-fit plateau). ---
sphi <- sphi.fix
k <- inv_trigamma(sphi^2); bg <- qgamma(0.5, k, rate=1)
cat(sprintf("Gamma prior init: sphi=%.2f -> shape k=%.3f rate=%.3f (median=1); est.sphi=%s\n",
            sphi, k, bg, est.sphi))

## per-AA response matrices + ref index
respi <- lapply(AAs, function(a){ cs<-codons.by.aa[[a]]; list(cs=cs, Y=CC[,cs,drop=FALSE],
            refi=match(ref.codon[a], cs)) }); names(respi) <- AAs

## storage for CSP params: per codon alpha,beta (ref=0) + their GLM SEs
alpha <- setNames(numeric(length(all.codons)), all.codons)
beta  <- setNames(numeric(length(all.codons)), all.codons)
alpha.se <- setNames(rep(NA_real_, length(all.codons)), all.codons)
beta.se  <- setNames(rep(NA_real_, length(all.codons)), all.codons)

loglik_total <- function(phi){
  ll <- 0
  for (a in AAs){ cs<-respi[[a]]$cs; Y<-respi[[a]]$Y
    eta <- outer(phi, beta[cs]) + matrix(alpha[cs], G, length(cs), byrow=TRUE)
    mx <- apply(eta,1,max); lse <- mx + log(rowSums(exp(eta-mx)))   # row-stable
    ll <- ll + sum(Y*(eta - lse)) }
  ll + sum((k-1)*log(phi) - bg*phi)
}

## Analytic per-gene phi update: damped Fisher-scoring on log(phi). The score
## is the multinomial (observed - expected) weighted by beta, plus the
## median-gauged Gamma prior; the (expected/Fisher) info is na*Var_p(beta) plus
## the prior curvature -- always >=0, so the step is stable. For a single
## rare-codon AA this reduces to the exact Poisson-Gamma (NB) posterior update.
## Returns updated phi AND the per-gene Fisher info in log-phi (for the joint
## sphi step and Laplace SEs). Vectorised over genes (loop is over ~19 AAs).
phi_fisher_step <- function(phi){
  th <- log(phi)
  for (nw in 1:6){
    p <- exp(th); sc <- numeric(G); fi <- numeric(G)
    for (a in AAs){ cs<-respi[[a]]$cs; Y<-respi[[a]]$Y; b<-beta[cs]
      eta <- outer(p,b) + matrix(alpha[cs],G,length(cs),byrow=TRUE)
      eta <- eta - apply(eta,1,max); ex<-exp(eta); pr<-ex/rowSums(ex)
      na <- rowSums(Y); ebar <- as.numeric(pr %*% b)
      sc <- sc + rowSums(Y*matrix(b,G,length(cs),byrow=TRUE)) - na*ebar
      fi <- fi + na*(as.numeric(pr %*% (b^2)) - ebar^2)
    }
    sc <- sc + (k-1)/p - bg                       # Gamma prior score
    fi <- pmax(fi + (k-1)/p^2, 1e-3)              # + prior info; floor for safety
    dth <- pmax(pmin(sc/(fi*p), 1), -1)           # Fisher step in log-phi, damped
    dth[!is.finite(dth)] <- 0
    th <- pmax(pmin(th + dth, 8), -8)
  }
  ## info.th must be evaluated at the FINAL th (the loop's fi/p are pre-step):
  ## recompute the phi-space Fisher info at the converged p before the log-phi curvature.
  p <- exp(th); fi <- numeric(G)
  for (a in AAs){ cs<-respi[[a]]$cs; Y<-respi[[a]]$Y; b<-beta[cs]
    eta <- outer(p,b) + matrix(alpha[cs],G,length(cs),byrow=TRUE)
    eta <- eta - apply(eta,1,max); pr <- exp(eta)/rowSums(exp(eta))
    na <- rowSums(Y); ebar <- as.numeric(pr %*% b)
    fi <- fi + na*(as.numeric(pr %*% (b^2)) - ebar^2)
  }
  fi <- pmax(fi + (k-1)/p^2, 1e-3)
  list(phi=setNames(exp(th),gid), fi=fi, info.th=fi*exp(2*th))   # info at the FINAL mode
}

## total multinomial log-lik (no prior), at current alpha/beta; row-stable
multinom_ll <- function(phi){ m <- 0
  for (a in AAs){ cs<-respi[[a]]$cs; Y<-respi[[a]]$Y
    eta <- outer(phi, beta[cs]) + matrix(alpha[cs],G,length(cs),byrow=TRUE)
    mx <- apply(eta,1,max); lse <- mx + log(rowSums(exp(eta-mx)))
    m <- m + sum(Y*(eta - lse)) }
  m }

## PER-GENE multinomial log-lik (G-vector), at current alpha/beta; row-stable.
multinom_ll_per_gene <- function(phi){ m <- numeric(G)
  for (a in AAs){ cs<-respi[[a]]$cs; Y<-respi[[a]]$Y
    eta <- outer(phi, beta[cs]) + matrix(alpha[cs],G,length(cs),byrow=TRUE)
    mx <- apply(eta,1,max); lse <- mx + log(rowSums(exp(eta-mx)))
    m <- m + rowSums(Y*(eta - lse)) }
  m }

## Proper marginal log-likelihood: integrate each gene's phi out under the
## median-gauged Gamma(k,bg) prior by ADAPTIVE Gauss-Hermite quadrature, holding
## alpha/beta (globals) fixed at the converged CSP values. Replaces the
## single-point Laplace term, which is artifactual for informative-per-gene data.
## We integrate in th = log(phi), where the integrand is more Gaussian:
##   M_g = int exp(g(th)) dth,  g(th) = mll_g(e^th) + k*th - bg*e^th + (k log bg - lgamma(k))
##   (the k*th - bg*e^th + const is log Gamma(e^th) + the d phi = e^th d th Jacobian).
## Centre each gene at the integrand mode (th.hat + 1/info.th, a one-step Newton
## correction of the phi-MAP for the Jacobian) and scale by 1/sqrt(info.th), then
## reweight the GH nodes by exp(x^2) (the standard adaptive-GHQ transform).
gh_logmarginal <- function(k, bg, th.hat, info.th){
  mu <- th.hat + 1/info.th                 # integrand (with-Jacobian) mode
  sig <- 1/sqrt(info.th)
  const <- k*log(bg) - lgamma(k)
  M <- matrix(-Inf, G, length(GHN$x))
  for (j in seq_along(GHN$x)){
    th <- pmax(pmin(mu + sqrt(2)*sig*GHN$x[j], 12), -12)   # cap to avoid Inf*0=NaN
    phi <- exp(th)
    g <- multinom_ll_per_gene(phi) + k*th - bg*phi + const
    M[,j] <- log(GHN$w[j]) + GHN$x[j]^2 + g
  }
  mx <- apply(M,1,max)
  logI <- mx + log(rowSums(exp(M - mx)))                   # log int-kernel sum / gene
  sum(log(sqrt(2)) + log(sig) + logI)                      # sum of per-gene log marginals
}

## Coordinate ascent (CSP <-> phi) at a FIXED sphi to convergence. Mutates the
## globals alpha/beta/alpha.se/beta.se/phi/k/bg; returns phi, the phi-space
## Fisher info at the mode (fi), and the LAPLACE-APPROX MARGINAL log-likelihood
## (integrate phi out, gene by gene, under the median-gauged Gamma(sphi) prior):
##   logML = sum_g [ multinom_ll(phi_g) + log Gamma(phi_g; k,bg) - 0.5 log fi_g ] + const
fit_inner <- function(sphi.val, phi.init, niter=20, verbose=FALSE){
  k <<- inv_trigamma(sphi.val^2); bg <<- qgamma(0.5, k, rate=1)
  phi <<- phi.init; prev <- -Inf; fs <- NULL
  for (it in 1:niter){
    for (a in AAs){ cs<-respi[[a]]$cs; refi<-respi[[a]]$refi
      Y<-respi[[a]]$Y; keep<-rowSums(Y)>0; ph<-phi[keep]; Yk<-Y[keep,,drop=FALSE]
      nonref<-cs[-refi]; alpha[cs]<<-0; beta[cs]<<-0      # skip-safe default (dM=dEta=0)
      ok.fit <- tryCatch({
        fit<-suppressWarnings(vglm(Yk~ph, multinomial(refLevel=refi)))
        cf<-coefvlm(fit,matrix=TRUE); se<-sqrt(diag(vcov(fit)))
        ai<-grep("Intercept",names(se)); bi<-grep("^ph",names(se))
        ## a sparse/aliased AA (a non-ref codon unobserved across kept genes) yields
        ## fewer columns -> skip rather than let R silently recycle a short vector.
        if (ncol(cf)!=length(nonref) || length(ai)!=length(nonref) || length(bi)!=length(nonref))
          stop("CSP dim mismatch")
        alpha[nonref]<<-cf[1,]; beta[nonref]<<-cf[2,]
        alpha.se[nonref]<<-se[ai]; beta.se[nonref]<<-se[bi]; TRUE
      }, error=function(e) FALSE)
      if (!ok.fit){ alpha.se[nonref]<<-NA; beta.se[nonref]<<-NA
        if (it==1) warning(sprintf("AA %s: CSP fit skipped (sparse/singular); dM=dEta=0 held", a), call.=FALSE) }
    }
    fs<-phi_fisher_step(phi); phi<<-fs$phi
    cur<-loglik_total(phi)
    if (verbose && (it<=2||it%%5==0)) cat(sprintf("    [sphi %.2f] it %2d logpost %.1f\n",sphi.val,it,cur))
    if (is.finite(prev) && abs(cur-prev)<1e-4*abs(prev)){ if(verbose) cat("    converged it",it,"\n"); break }
    prev<-cur
  }
  mll <- multinom_ll(phi); gll <- sum(dgamma(phi, shape=k, rate=bg, log=TRUE))
  lap <- -0.5*sum(log(fs$fi)) + 0.5*G*log(2*pi)
  logML.gh <- gh_logmarginal(k, bg, log(phi), fs$info.th)   # proper GH-quadrature marginal
  list(phi=phi, fi=fs$fi, info.th=fs$info.th, logML=mll+gll+lap, logML.gh=logML.gh,
       mll=mll, gll=gll, lap=lap, k=k, bg=bg)
}

ref <- read.csv(phi.ref)                         # native phi reference (read once)
if (!est.sphi) {
  cat("Fitting at fixed sphi =", sphi.fix, "\n")
  res <- fit_inner(sphi.fix, phi, verbose=verbose); sphi <- sphi.fix; sphi.se <- NA
} else {
  ## sphi profile over a grid. PRIMARY estimator = the adaptive Gauss-Hermite
  ## marginal (logML.gh): it integrates each gene's phi out properly and, unlike
  ## the single-point Laplace marginal (logML, monotone/artifactual here),
  ## peaks at a finite sphi. We also report the data-fit (multinomial LL) plateau
  ## as an independent cross-check: it improves then flattens once the dEta*phi
  ## scale degeneracy kicks in. sphi-hat = the interior GH-marginal maximum (a
  ## local parabola on the bracketing grid points gives the vertex + curvature
  ## SE); if the GH max is at a grid boundary we fall back to the data-fit plateau.
  phi0 <- phi   # clean PC1 init (the good basin); reuse for the final refit
  grid <- seq(0.4, 1.8, by=0.2); ml.lap <- ml.gh <- mll.v <- numeric(length(grid)); warm <- phi
  cat("sphi profile (GH-quadrature marginal vs Laplace vs data-fit):\n")
  m0 <- NA
  for (i in seq_along(grid)){ r <- fit_inner(grid[i], warm)
    ml.lap[i] <- r$logML; ml.gh[i] <- r$logML.gh; mll.v[i] <- r$mll; warm <- r$phi
    if(i==1) m0 <- r$mll
    cat(sprintf("  sphi=%.2f  dataFitLL=%+.1f  logML_Laplace=%.1f  logML_GH=%.1f\n",
                grid[i], r$mll-m0, ml.lap[i], ml.gh[i])) }
  ## data-fit plateau (independent cross-check); fall back to the data-fit argmax
  ## if mll.v never rises to 95% of its range (non-increasing -> which() empty -> NA).
  tot <- max(mll.v) - min(mll.v)
  pix <- which(cumsum(c(0, diff(mll.v))) >= 0.95*tot)[1]
  sphi.plateau <- if (is.na(pix)) grid[which.max(mll.v)] else grid[pix]
  ## GH-marginal MAP + curvature SE (parabola on the 3 bracketing grid points)
  i.gh <- which.max(ml.gh); sphi.gh <- grid[i.gh]; sphi.se <- NA
  interior <- i.gh > 1 && i.gh < length(grid)
  if (interior){
    xx <- grid[(i.gh-1):(i.gh+1)]; yy <- ml.gh[(i.gh-1):(i.gh+1)]
    qc <- coef(lm(yy ~ poly(xx, 2, raw=TRUE))); a2 <- qc[3]
    if (is.finite(a2) && a2 < 0){
      sphi.gh <- min(max(as.numeric(-qc[2]/(2*a2)), xx[1]), xx[3])  # clamp vertex to bracket
      sphi.se <- 1/sqrt(-2*a2) }
  }
  sphi <- if (interior) sphi.gh else sphi.plateau
  res <- fit_inner(sphi, phi0)                 # final fit at sphi-hat from the clean init
  cat(sprintf("=> GH-marginal sphi-hat = %.3f%s%s ; data-fit plateau = %.3f ; native = %.3f\n",
              sphi.gh, if (is.finite(sphi.se)) sprintf(" (SE %.3f)", sphi.se) else "",
              if (!interior) " [boundary -> used plateau]" else "",
              sphi.plateau, sd(ref$log_phi)))
}
fs <- list(info.th = res$info.th)              # for the SE block below

## --- validation ---
common <- intersect(names(phi), ref$gene_id)
myl <- log(phi)[common]; rl <- ref$log_phi[match(common, ref$gene_id)]
cat(sprintf("\nVALIDATION (n=%d common genes)\n", length(common)))
cat(sprintf("  phi : Pearson=%.3f  Spearman=%.3f vs native ROC fit\n",
            cor(myl,rl), cor(myl,rl,method="spearman")))
cm <- match(det$Codon, names(beta)); ok <- !is.na(cm) & abs(det$Mean)>1e-12
cat(sprintf("  dEta: Pearson=%.3f (n=%d non-ref codons) vs published\n",
            cor(beta[cm[ok]], det$Mean[ok]), sum(ok)))
dmm <- match(dMt$Codon, names(alpha)); okm <- !is.na(dmm) & abs(dMt$Mean)>1e-12
cat(sprintf("  dM  : Pearson=%.3f (n=%d non-ref codons) vs published\n",
            cor(alpha[dmm[okm]], dMt$Mean[okm]), sum(okm)))
cat(sprintf("  sphi: %s=%.3f%s  (SD of log-phi modes=%.3f)  vs native-fit SD(log phi)=%.3f\n",
            if (est.sphi) "estimated" else "fixed", sphi,
            if (est.sphi && is.finite(sphi.se)) sprintf(" (SE %.3f)", sphi.se) else "",
            sd(log(phi)), sd(rl)))

## --- Laplace / GLM standard errors ---
phi.se.log <- setNames(1/sqrt(fs$info.th), gid)          # per-gene SE of log(phi) (Laplace, from Fisher info)
okc <- !is.na(beta.se)                                    # non-ref codons
cat(sprintf("\nSTANDARD ERRORS\n  SE(log phi): median=%.3f  IQR=[%.3f, %.3f]\n",
            median(phi.se.log), quantile(phi.se.log,.25), quantile(phi.se.log,.75)))
cat(sprintf("  SE(dEta) median=%.3f ; SE(dM) median=%.3f  (%d non-ref codons)\n",
            median(beta.se[okc]), median(alpha.se[okc]), sum(okc)))
cov2 <- mean(abs(myl - rl) <= 2*phi.se.log[common])      # native within my estimate +/- 2 SE
cat(sprintf("  phi coverage: native log-phi within est +/- 2*SE for %.1f%% of genes\n", 100*cov2))
out.pre <- sub("\\.png$","",png.out)
write.csv(data.frame(gene=gid, phi=as.numeric(phi), log_phi=log(as.numeric(phi)),
          se_log_phi=as.numeric(phi.se.log)), paste0(out.pre,"_phi.csv"), row.names=FALSE)
csp.aa <- rep(AAs, vapply(codons.by.aa[AAs], length, 1L))
write.csv(data.frame(AA=csp.aa, codon=all.codons,
          dM=alpha[all.codons], dM_se=alpha.se[all.codons],
          dEta=beta[all.codons], dEta_se=beta.se[all.codons]),
          paste0(out.pre,"_csp.csv"), row.names=FALSE)
cat("  wrote ", out.pre, "_phi.csv + _csp.csv\n", sep="")

png(png.out, width=1500, height=520, res=110); par(mfrow=c(1,3), mar=c(4.3,4.3,3,1))
plot(myl, rl, pch=19, col=rgb(0,0,0,.25), cex=.5, xlab="GLM-EM log(phi)", ylab="native ROC log(phi)",
     main=sprintf("phi recovery r=%.2f", cor(myl,rl))); abline(lm(rl~myl), col="firebrick", lwd=2)
plot(beta[cm[ok]], det$Mean[ok], pch=19, col=rgb(0,0,1,.4), xlab="GLM-EM beta (dEta)", ylab="published dEta",
     main=sprintf("dEta r=%.2f", cor(beta[cm[ok]], det$Mean[ok]))); abline(0,0,col="grey",lty=3); abline(v=0,col="grey",lty=3)
plot(alpha[dmm[okm]], dMt$Mean[okm], pch=19, col=rgb(0,.5,0,.4), xlab="GLM-EM alpha (dM)", ylab="published dM",
     main=sprintf("dM r=%.2f", cor(alpha[dmm[okm]], dMt$Mean[okm]))); abline(0,0,col="grey",lty=3); abline(v=0,col="grey",lty=3)
dev.off(); cat("wrote", png.out, "\n")
