#!/usr/bin/env Rscript
# ============================================================================
# Script:       fit.roc.glm.em.R
# Version:      0.8.0
# Created:      2026-06-17
# Revised:      2026-06-19
# Purpose:      Fit the ROC codon model as a multinomial GLMM by coordinate
#               ascent (IRLS-EM) -- a fast, deterministic alternative to native
#               MCMC. CSP step = per-AA multinomial logistic GLM (codon ~ phi);
#               phi step = per-gene analytic damped Fisher-scoring (the NB /
#               Poisson-Gamma update) + a median-gauged Gamma(sphi) prior (the
#               prior pins the scale, so no separate gauge step). Laplace SEs for
#               phi/dM/dEta. sphi (= SD log phi) is weakly identified from codon
#               data; --est-sphi profiles a proper ADAPTIVE GAUSS-HERMITE
#               marginal (integrates each gene's phi out; the single-point
#               Laplace marginal is artifactual and monotone -- both are reported
#               for comparison, plus the data-fit plateau cross-check). Default
#               is fixed --sphi. See notes/sphi-Ne-metrics-gamma-theory.md.
#
#               DATA: by default the script is SELF-CONTAINED -- it SIMULATES a
#               ROC genome from known dM/dEta/phi (like prototypes/phi_mixture.R)
#               and validates recovery against that truth. Pass --fasta + --deta
#               + --dM + --phi-ref to fit a real genome against external native
#               ROC references instead.
#
#               ROC log-odds linearity:  log P(codon c | gene g)/P(ref) =
#               dM_c + dEta_c * phi_g  -> given phi it is a multinomial GLM,
#               given the GLM it is a per-gene 1-D solve.
#
# Usage:        Rscript fit.roc.glm.em.R [--sphi N] [--est-sphi T/F] [--png F]
#                 simulate (default): [--n-genes N] [--sim-sphi N] [--seed N]
#                                     [--sim-phi-dist gamma|lognormal]
#                 real data:          [--fasta F] [--deta CSV] [--dM CSV] [--phi-ref CSV]
#                 common:             [--lib DIR] [--verbose T/F] [--dry-run] [--help]
#
# Provenance:   Promoted from Analyses-RibModelFramework roc/scripts/ @ 0476b94
#               (2026-06-19); see that repo's roc/notes/ for the exploratory
#               history. (v0.8 added simulate-by-default so the prototype carries
#               no external-path dependency, consistent with the other prototypes.)
#
# Sourcing:     `source()`-ing this file defines the functions WITHOUT running the
#               CLI (the main() call is guarded by sys.nframe()==0), so it is
#               testable -- see prototypes/fit_roc_glm_em_check.R.
#
# Options:
#   --dry-run   Resolve + validate config (and input files in real mode), then exit
#   --verbose   Print the per-iteration convergence trace (default TRUE)
#   --help      Print this usage block and exit
#
# Output:       stdout: convergence trace + validation (dM/dEta/phi recovery vs
#                       the simulated truth, or vs the native references); PNG.
#
# Session:      ROC sphi/Ne/metrics theory -> GLM-EM prototype
# AI Model:     Claude Opus 4.8
# Attribution:  Generated by Michael Gilchrist in collaboration with Claude Opus 4.8
# ============================================================================

# ============================================================================
# 0. Small helpers (read-only; safe to source)
# ============================================================================

inv_trigamma <- function(t) uniroot(function(k) trigamma(k)-t, c(1e-3,1e6))$root

## Gauss-Hermite nodes/weights for the physicists' weight exp(-x^2), via the
## Golub-Welsch algorithm (eigendecomposition of the symmetric tridiagonal
## Jacobi matrix). Pure base R, no external quadrature package needed.
gh_nodes <- function(n){
  if (n==1) return(list(x=0, w=sqrt(pi)))
  j <- 1:(n-1); b <- sqrt(j/2)
  J <- matrix(0, n, n); J[cbind(j,j+1)] <- b; J[cbind(j+1,j)] <- b
  e <- eigen(J, symmetric=TRUE); o <- order(e$values)
  list(x=e$values[o], w=(sqrt(pi)*e$vectors[1,]^2)[o])
}
GHN <- gh_nodes(20)

# ============================================================================
# 1. Simulate a ROC genome from known dM/dEta/phi (self-contained default)
# ============================================================================
## Returns the same structure prepare_genome_from_files() does, plus `truth`.
## Codon labels are synthetic ("AA01_c2", ...); the reference codon per AA is
## pinned (dM=dEta=0). phi ~ median-gauged Gamma(sphi). Counts per gene per AA
## are Multinomial(Poisson(mean.count), softmax(dM + dEta*phi)) -- the SAME
## log-odds(c/ref) = dM + dEta*phi convention the fitter recovers, so recovered
## dM/dEta/phi correlate POSITIVELY with truth (no sign flip in simulate mode).
simulate_roc_genome <- function(n.genes=500, sphi=1.0, seed=1,
                                phi.dist=c("gamma","lognormal"),
                                degeneracy=c(rep(2,9), 3, rep(4,5), rep(6,2)),
                                sd.dM=0.6, sd.dEta=0.5, mean.count=12){
  phi.dist <- match.arg(phi.dist)
  set.seed(seed)
  nAA <- length(degeneracy)
  AAs <- sprintf("AA%02d", seq_len(nAA))
  codons.by.aa <- setNames(lapply(seq_len(nAA), function(i)
      sprintf("%s_c%d", AAs[i], seq_len(degeneracy[i]))), AAs)
  ref.codon  <- setNames(vapply(codons.by.aa, function(cs) cs[1], ""), AAs)  # ref = first codon
  all.codons <- unlist(codons.by.aa, use.names=FALSE)
  ## truth CSP: reference pinned 0; non-ref drawn
  dM   <- setNames(numeric(length(all.codons)), all.codons)
  dEta <- setNames(numeric(length(all.codons)), all.codons)
  for (a in AAs){ nr <- codons.by.aa[[a]][-1]
    dM[nr]   <- rnorm(length(nr), 0, sd.dM)
    dEta[nr] <- rnorm(length(nr), 0, sd.dEta) }
  ## truth phi from a median-gauged distribution: median(phi)=1, SD(log phi)=sphi.
  ## 'gamma' matches the GLMM prior; 'lognormal' matches native/Stan. Recovery of
  ## dM/dEta/phi should be good EITHER way -- the codon<->phi (multinomial logit)
  ## relation is prior-shape agnostic; the prior only weakly regularises phi.
  gid <- sprintf("g%04d", seq_len(n.genes))
  if (phi.dist == "gamma"){
    k <- inv_trigamma(sphi^2); rate <- qgamma(0.5, k, rate=1)
    phi <- setNames(rgamma(n.genes, shape=k, rate=rate), gid)
  } else {                                            # median-gauged lognormal
    phi <- setNames(exp(rnorm(n.genes, 0, sphi)), gid)
  }
  ## counts CC[gene, codon]
  CC <- matrix(0L, n.genes, length(all.codons), dimnames=list(gid, all.codons))
  for (a in AAs){ cs <- codons.by.aa[[a]]
    eta <- outer(phi, dEta[cs]) + matrix(dM[cs], n.genes, length(cs), byrow=TRUE)
    eta <- eta - apply(eta,1,max); P <- exp(eta)/rowSums(exp(eta))
    na <- rpois(n.genes, mean.count)
    for (g in seq_len(n.genes)) if (na[g] > 0) CC[g, cs] <- rmultinom(1, na[g], P[g,])
  }
  list(CC=CC, AAs=AAs, codons.by.aa=codons.by.aa, ref.codon=ref.codon,
       all.codons=all.codons, gid=gid,
       truth=list(dM=dM, dEta=dEta, phi=phi, sphi=sphi, phi.dist=phi.dist))
}

# ============================================================================
# 2. Prepare a genome from real files (FASTA + published dM/dEta CSVs)
# ============================================================================
## AA groups + reference codon are taken FROM the published dEta CSV so the
## grouping/reference convention matches AnaCoDa exactly.
prepare_genome_from_files <- function(fasta, deta.f, dM.f){
  det <- read.csv(deta.f); dMt <- read.csv(dM.f)
  aa.list <- split(det, det$AA)                       # AA -> data.frame(Codon, Mean,...)
  aa.list <- aa.list[vapply(aa.list, nrow, 1L) >= 2]  # degenerate AAs only
  AAs <- names(aa.list)
  # reference codon per AA = the one with published Mean exactly 0 (AnaCoDa pins it)
  ref.codon <- vapply(aa.list, function(d){ r <- d$Codon[abs(d$Mean) < 1e-12]; if(length(r)) r[1] else tail(d$Codon,1) }, "")
  codons.by.aa <- lapply(aa.list, function(d) d$Codon)
  all.codons <- unlist(codons.by.aa, use.names=FALSE)
  ## read FASTA, count codons per gene
  ln <- readLines(fasta, warn=FALSE); h <- grepl("^>", ln)
  gid <- sub("^>([^ ]+).*","\\1", ln[h]); grp <- cumsum(h)
  seqs <- toupper(tapply(ln[!h], grp[!h], paste0, collapse="")); seqs <- setNames(unname(seqs), gid)
  ccount <- function(s){ n<-nchar(s); if(n<3) return(setNames(integer(length(all.codons)),all.codons))
    table(factor(substring(s,seq(1,n-2,3),seq(3,n,3)), levels=all.codons)) }
  CC <- t(vapply(seqs, ccount, integer(length(all.codons)))); colnames(CC) <- all.codons
  list(CC=CC, AAs=AAs, codons.by.aa=codons.by.aa, ref.codon=ref.codon,
       all.codons=all.codons, gid=gid, det=det, dMt=dMt)
}

# ============================================================================
# 3. Robust phi initialisation: PC1 of the 2-fold focal fractions (mode anchor)
# ============================================================================
init_phi_pc1 <- function(CC, AAs, codons.by.aa, gid){
  two <- AAs[vapply(codons.by.aa[AAs], length, 1L)==2]
  Fr <- sapply(two, function(a){ cs<-codons.by.aa[[a]]; CC[,cs[1]]/(CC[,cs[1]]+CC[,cs[2]]) })
  Fr[!is.finite(Fr)] <- NA; cm<-colMeans(Fr,na.rm=TRUE); for(j in seq_len(ncol(Fr))) Fr[is.na(Fr[,j]),j]<-cm[j]
  pc <- prcomp(scale(Fr,center=TRUE,scale=FALSE))$x[,1]
  if (cor(pc, rowMeans(abs(sweep(Fr,2,cm)))) < 0) pc <- -pc
  phi <- setNames(exp((pc-median(pc))/sd(pc)), gid); phi/median(phi)
}

# ============================================================================
# 4. Core fitter: ROC GLM-EM at fixed sphi, or profiled --est-sphi
# ============================================================================
## `data` = the list from simulate_roc_genome() / prepare_genome_from_files().
## Returns the recovered phi/dM(alpha)/dEta(beta) + their SEs, sphi(+SE), and the
## per-gene log-phi Fisher info. The inner functions are closures over this
## frame; their `<<-` writes target these locals (NOT the global env), so the
## numerics are identical to running the flat script. Requires VGAM loaded.
fit_roc_glm_em <- function(data, sphi.fix=1.0, est.sphi=FALSE, phi.init=NULL, verbose=FALSE){
  CC <- data$CC; AAs <- data$AAs; codons.by.aa <- data$codons.by.aa
  ref.codon <- data$ref.codon; all.codons <- data$all.codons; gid <- data$gid
  G <- nrow(CC)
  ## per-AA response matrices + ref index
  respi <- lapply(AAs, function(a){ cs<-codons.by.aa[[a]]; list(cs=cs, Y=CC[,cs,drop=FALSE],
              refi=match(ref.codon[a], cs)) }); names(respi) <- AAs
  ## storage for CSP params + their GLM SEs; k/bg/phi set by fit_inner via <<-
  alpha <- setNames(numeric(length(all.codons)), all.codons)
  beta  <- setNames(numeric(length(all.codons)), all.codons)
  alpha.se <- setNames(rep(NA_real_, length(all.codons)), all.codons)
  beta.se  <- setNames(rep(NA_real_, length(all.codons)), all.codons)
  k <- NA_real_; bg <- NA_real_; phi <- NULL

  loglik_total <- function(phi){
    ll <- 0
    for (a in AAs){ cs<-respi[[a]]$cs; Y<-respi[[a]]$Y
      eta <- outer(phi, beta[cs]) + matrix(alpha[cs], G, length(cs), byrow=TRUE)
      mx <- apply(eta,1,max); lse <- mx + log(rowSums(exp(eta-mx)))   # row-stable
      ll <- ll + sum(Y*(eta - lse)) }
    ll + sum((k-1)*log(phi) - bg*phi)
  }

  ## Analytic per-gene phi update: damped Fisher-scoring on log(phi). Score =
  ## multinomial (observed - expected) weighted by beta, plus the median-gauged
  ## Gamma prior; info = na*Var_p(beta) + prior curvature (>=0, so stable). For a
  ## single rare-codon AA this reduces to the exact Poisson-Gamma (NB) update.
  phi_fisher_step <- function(phi){
    th <- log(phi)
    for (nw in 1:6){
      p <- exp(th); sc <- numeric(G); fi <- numeric(G)
      for (a in AAs){ cs<-respi[[a]]$cs; Y<-respi[[a]]$Y; b<-beta[cs]
        eta <- outer(p,b) + matrix(alpha[cs],G,length(cs),byrow=TRUE)
        eta <- eta - apply(eta,1,max); ex<-exp(eta); pr<-ex/rowSums(ex)
        na <- rowSums(Y); ebar <- as.numeric(pr %*% b)
        sc <- sc + rowSums(Y*matrix(b,G,length(cs),byrow=TRUE)) - na*ebar
        fi <- fi + na*(as.numeric(pr %*% (b^2)) - ebar^2)
      }
      sc <- sc + (k-1)/p - bg                       # Gamma prior score
      fi <- pmax(fi + (k-1)/p^2, 1e-3)              # + prior info; floor for safety
      dth <- pmax(pmin(sc/(fi*p), 1), -1)           # Fisher step in log-phi, damped
      dth[!is.finite(dth)] <- 0
      th <- pmax(pmin(th + dth, 8), -8)
    }
    ## info.th must be evaluated at the FINAL th (the loop's fi/p are pre-step):
    ## recompute the phi-space Fisher info at the converged p before the log-phi curvature.
    p <- exp(th); fi <- numeric(G)
    for (a in AAs){ cs<-respi[[a]]$cs; Y<-respi[[a]]$Y; b<-beta[cs]
      eta <- outer(p,b) + matrix(alpha[cs],G,length(cs),byrow=TRUE)
      eta <- eta - apply(eta,1,max); pr <- exp(eta)/rowSums(exp(eta))
      na <- rowSums(Y); ebar <- as.numeric(pr %*% b)
      fi <- fi + na*(as.numeric(pr %*% (b^2)) - ebar^2)
    }
    fi <- pmax(fi + (k-1)/p^2, 1e-3)
    list(phi=setNames(exp(th),gid), fi=fi, info.th=fi*exp(2*th))   # info at the FINAL mode
  }

  ## total multinomial log-lik (no prior), at current alpha/beta; row-stable
  multinom_ll <- function(phi){ m <- 0
    for (a in AAs){ cs<-respi[[a]]$cs; Y<-respi[[a]]$Y
      eta <- outer(phi, beta[cs]) + matrix(alpha[cs],G,length(cs),byrow=TRUE)
      mx <- apply(eta,1,max); lse <- mx + log(rowSums(exp(eta-mx)))
      m <- m + sum(Y*(eta - lse)) }
    m }

  ## PER-GENE multinomial log-lik (G-vector), at current alpha/beta; row-stable.
  multinom_ll_per_gene <- function(phi){ m <- numeric(G)
    for (a in AAs){ cs<-respi[[a]]$cs; Y<-respi[[a]]$Y
      eta <- outer(phi, beta[cs]) + matrix(alpha[cs],G,length(cs),byrow=TRUE)
      mx <- apply(eta,1,max); lse <- mx + log(rowSums(exp(eta-mx)))
      m <- m + rowSums(Y*(eta - lse)) }
    m }

  ## Proper marginal log-likelihood: integrate each gene's phi out under the
  ## median-gauged Gamma(k,bg) prior by ADAPTIVE Gauss-Hermite quadrature, holding
  ## alpha/beta fixed at the converged CSP values. Integrate in th = log(phi):
  ##   M_g = int exp(g(th)) dth, g(th)=mll_g(e^th)+k*th-bg*e^th+(k log bg-lgamma(k))
  ## Centre at the integrand mode (th.hat + 1/info.th) and scale by 1/sqrt(info.th).
  gh_logmarginal <- function(k, bg, th.hat, info.th){
    mu <- th.hat + 1/info.th                 # integrand (with-Jacobian) mode
    sig <- 1/sqrt(info.th)
    const <- k*log(bg) - lgamma(k)
    M <- matrix(-Inf, G, length(GHN$x))
    for (j in seq_along(GHN$x)){
      th <- pmax(pmin(mu + sqrt(2)*sig*GHN$x[j], 12), -12)   # cap to avoid Inf*0=NaN
      phi <- exp(th)
      g <- multinom_ll_per_gene(phi) + k*th - bg*phi + const
      M[,j] <- log(GHN$w[j]) + GHN$x[j]^2 + g
    }
    mx <- apply(M,1,max)
    logI <- mx + log(rowSums(exp(M - mx)))                   # log int-kernel sum / gene
    sum(log(sqrt(2)) + log(sig) + logI)                      # sum of per-gene log marginals
  }

  ## Coordinate ascent (CSP <-> phi) at a FIXED sphi to convergence. Mutates the
  ## frame's alpha/beta/alpha.se/beta.se/phi/k/bg; returns phi, the phi-space
  ## Fisher info, the Laplace marginal, and the proper GH-quadrature marginal.
  fit_inner <- function(sphi.val, phi.init, niter=20, verbose=FALSE){
    k <<- inv_trigamma(sphi.val^2); bg <<- qgamma(0.5, k, rate=1)
    phi <<- phi.init; prev <- -Inf; fs <- NULL
    for (it in 1:niter){
      for (a in AAs){ cs<-respi[[a]]$cs; refi<-respi[[a]]$refi
        Y<-respi[[a]]$Y; keep<-rowSums(Y)>0; ph<-phi[keep]; Yk<-Y[keep,,drop=FALSE]
        nonref<-cs[-refi]; alpha[cs]<<-0; beta[cs]<<-0      # skip-safe default (dM=dEta=0)
        ok.fit <- tryCatch({
          fit<-suppressWarnings(vglm(Yk~ph, multinomial(refLevel=refi)))
          cf<-coefvlm(fit,matrix=TRUE); se<-sqrt(diag(vcov(fit)))
          ai<-grep("Intercept",names(se)); bi<-grep("^ph",names(se))
          ## a sparse/aliased AA (a non-ref codon unobserved across kept genes) yields
          ## fewer columns -> skip rather than let R silently recycle a short vector.
          if (ncol(cf)!=length(nonref) || length(ai)!=length(nonref) || length(bi)!=length(nonref))
            stop("CSP dim mismatch")
          alpha[nonref]<<-cf[1,]; beta[nonref]<<-cf[2,]
          alpha.se[nonref]<<-se[ai]; beta.se[nonref]<<-se[bi]; TRUE
        }, error=function(e) FALSE)
        if (!ok.fit){ alpha.se[nonref]<<-NA; beta.se[nonref]<<-NA
          if (it==1) warning(sprintf("AA %s: CSP fit skipped (sparse/singular); dM=dEta=0 held", a), call.=FALSE) }
      }
      fs<-phi_fisher_step(phi); phi<<-fs$phi
      cur<-loglik_total(phi)
      if (verbose && (it<=2||it%%5==0)) cat(sprintf("    [sphi %.2f] it %2d logpost %.1f\n",sphi.val,it,cur))
      if (is.finite(prev) && abs(cur-prev)<1e-4*abs(prev)){ if(verbose) cat("    converged it",it,"\n"); break }
      prev<-cur
    }
    mll <- multinom_ll(phi); gll <- sum(dgamma(phi, shape=k, rate=bg, log=TRUE))
    lap <- -0.5*sum(log(fs$fi)) + 0.5*G*log(2*pi)
    logML.gh <- gh_logmarginal(k, bg, log(phi), fs$info.th)   # proper GH-quadrature marginal
    list(phi=phi, fi=fs$fi, info.th=fs$info.th, logML=mll+gll+lap, logML.gh=logML.gh,
         mll=mll, gll=gll, lap=lap, k=k, bg=bg)
  }

  if (is.null(phi.init)) phi.init <- init_phi_pc1(CC, AAs, codons.by.aa, gid)
  phi <- phi.init
  cat(sprintf("AAs: %d   sense codons modelled: %d   genes: %d\n",
              length(AAs), length(all.codons), G))

  if (!est.sphi){
    cat("Fitting at fixed sphi =", sphi.fix, "\n")
    res <- fit_inner(sphi.fix, phi, verbose=verbose); sphi <- sphi.fix; sphi.se <- NA
  } else {
    ## sphi profile. PRIMARY estimator = adaptive GH marginal (logML.gh); it
    ## integrates phi out properly. Data-fit (multinomial LL) plateau is reported
    ## as an independent cross-check. (On codon data alone the marginal is
    ## typically monotone -- sphi is only weakly identified; see the theory note.)
    phi0 <- phi   # clean PC1 init (the good basin); reuse for the final refit
    grid <- seq(0.4, 1.8, by=0.2); ml.lap <- ml.gh <- mll.v <- numeric(length(grid)); warm <- phi
    cat("sphi profile (GH-quadrature marginal vs Laplace vs data-fit):\n")
    m0 <- NA
    for (i in seq_along(grid)){ r <- fit_inner(grid[i], warm)
      ml.lap[i] <- r$logML; ml.gh[i] <- r$logML.gh; mll.v[i] <- r$mll; warm <- r$phi
      if(i==1) m0 <- r$mll
      cat(sprintf("  sphi=%.2f  dataFitLL=%+.1f  logML_Laplace=%.1f  logML_GH=%.1f\n",
                  grid[i], r$mll-m0, ml.lap[i], ml.gh[i])) }
    ## data-fit plateau; fall back to the data-fit argmax if mll.v never rises to
    ## 95% of its range (non-increasing -> which() empty -> NA).
    tot <- max(mll.v) - min(mll.v)
    pix <- which(cumsum(c(0, diff(mll.v))) >= 0.95*tot)[1]
    sphi.plateau <- if (is.na(pix)) grid[which.max(mll.v)] else grid[pix]
    ## GH-marginal MAP + curvature SE (parabola on the 3 bracketing grid points)
    i.gh <- which.max(ml.gh); sphi.gh <- grid[i.gh]; sphi.se <- NA
    interior <- i.gh > 1 && i.gh < length(grid)
    if (interior){
      xx <- grid[(i.gh-1):(i.gh+1)]; yy <- ml.gh[(i.gh-1):(i.gh+1)]
      qc <- coef(lm(yy ~ poly(xx, 2, raw=TRUE))); a2 <- qc[3]
      if (is.finite(a2) && a2 < 0){
        sphi.gh <- min(max(as.numeric(-qc[2]/(2*a2)), xx[1]), xx[3])  # clamp vertex to bracket
        sphi.se <- 1/sqrt(-2*a2) }
    }
    sphi <- if (interior) sphi.gh else sphi.plateau
    res <- fit_inner(sphi, phi0)                 # final fit at sphi-hat from the clean init
    cat(sprintf("=> GH-marginal sphi-hat = %.3f%s%s ; data-fit plateau = %.3f\n",
                sphi.gh, if (is.finite(sphi.se)) sprintf(" (SE %.3f)", sphi.se) else "",
                if (!interior) " [boundary -> used plateau]" else "", sphi.plateau))
  }

  list(phi=phi, alpha=alpha, beta=beta, alpha.se=alpha.se, beta.se=beta.se,
       sphi=sphi, sphi.se=sphi.se, est.sphi=est.sphi, info.th=res$info.th,
       AAs=AAs, codons.by.aa=codons.by.aa, all.codons=all.codons, gid=gid)
}

# ============================================================================
# 5. Validation + reporting (recovery vs truth or vs native references)
# ============================================================================
## ref.dM / ref.dEta are named-by-codon; ref.logphi named-by-gene. Correlations
## are computed on the common, non-reference (non-zero) codons / common genes.
## Returns the validation stats (used by the check script).
report_and_plot <- function(res, ref.dM, ref.dEta, ref.logphi, ref.sphi.sd, ref.label, png.out){
  phi <- res$phi; alpha <- res$alpha; beta <- res$beta; gid <- res$gid
  ## phi
  common <- intersect(names(phi), names(ref.logphi))
  myl <- log(phi)[common]; rl <- ref.logphi[common]
  r.phi.p <- cor(myl, rl); r.phi.s <- cor(myl, rl, method="spearman")
  ## dEta
  ce <- intersect(names(beta), names(ref.dEta)); ce <- ce[abs(ref.dEta[ce]) > 1e-12]
  r.dEta <- cor(beta[ce], ref.dEta[ce])
  ## dM
  cmm <- intersect(names(alpha), names(ref.dM)); cmm <- cmm[abs(ref.dM[cmm]) > 1e-12]
  r.dM <- cor(alpha[cmm], ref.dM[cmm])

  cat(sprintf("\nVALIDATION (n=%d common genes) vs %s\n", length(common), ref.label))
  cat(sprintf("  phi : Pearson=%.3f  Spearman=%.3f\n", r.phi.p, r.phi.s))
  cat(sprintf("  dEta: Pearson=%.3f (n=%d non-ref codons)\n", r.dEta, length(ce)))
  cat(sprintf("  dM  : Pearson=%.3f (n=%d non-ref codons)\n", r.dM, length(cmm)))
  cat(sprintf("  sphi: %s=%.3f%s  (SD of log-phi modes=%.3f)  vs ref SD(log phi)=%.3f\n",
              if (res$est.sphi) "estimated" else "fixed", res$sphi,
              if (res$est.sphi && is.finite(res$sphi.se)) sprintf(" (SE %.3f)", res$sphi.se) else "",
              sd(log(phi)), ref.sphi.sd))

  ## Laplace / GLM standard errors
  phi.se.log <- setNames(1/sqrt(res$info.th), gid)
  okc <- !is.na(res$beta.se)
  cat(sprintf("STANDARD ERRORS\n  SE(log phi): median=%.3f  IQR=[%.3f, %.3f]\n",
              median(phi.se.log), quantile(phi.se.log,.25), quantile(phi.se.log,.75)))
  cat(sprintf("  SE(dEta) median=%.3f ; SE(dM) median=%.3f  (%d non-ref codons)\n",
              median(res$beta.se[okc]), median(res$alpha.se[okc]), sum(okc)))
  cov2 <- mean(abs(myl - rl) <= 2*phi.se.log[common])
  cat(sprintf("  phi coverage: ref log-phi within est +/- 2*SE for %.1f%% of genes\n", 100*cov2))

  ## CSV export
  out.pre <- sub("\\.png$","",png.out)
  write.csv(data.frame(gene=gid, phi=as.numeric(phi), log_phi=log(as.numeric(phi)),
            se_log_phi=as.numeric(phi.se.log)), paste0(out.pre,"_phi.csv"), row.names=FALSE)
  csp.aa <- rep(res$AAs, vapply(res$codons.by.aa[res$AAs], length, 1L))
  write.csv(data.frame(AA=csp.aa, codon=res$all.codons,
            dM=alpha[res$all.codons], dM_se=res$alpha.se[res$all.codons],
            dEta=beta[res$all.codons], dEta_se=res$beta.se[res$all.codons]),
            paste0(out.pre,"_csp.csv"), row.names=FALSE)
  cat("  wrote ", out.pre, "_phi.csv + _csp.csv\n", sep="")

  ## diagnostic plot
  png(png.out, width=1500, height=520, res=110); par(mfrow=c(1,3), mar=c(4.3,4.3,3,1))
  plot(myl, rl, pch=19, col=rgb(0,0,0,.25), cex=.5, xlab="GLM-EM log(phi)", ylab=sprintf("%s log(phi)", ref.label),
       main=sprintf("phi recovery r=%.2f", r.phi.p)); abline(lm(rl~myl), col="firebrick", lwd=2)
  plot(beta[ce], ref.dEta[ce], pch=19, col=rgb(0,0,1,.4), xlab="GLM-EM beta (dEta)", ylab=sprintf("%s dEta", ref.label),
       main=sprintf("dEta r=%.2f", r.dEta)); abline(0,0,col="grey",lty=3); abline(v=0,col="grey",lty=3)
  plot(alpha[cmm], ref.dM[cmm], pch=19, col=rgb(0,.5,0,.4), xlab="GLM-EM alpha (dM)", ylab=sprintf("%s dM", ref.label),
       main=sprintf("dM r=%.2f", r.dM)); abline(0,0,col="grey",lty=3); abline(v=0,col="grey",lty=3)
  dev.off(); cat("wrote", png.out, "\n")

  invisible(list(r.phi.pearson=r.phi.p, r.phi.spearman=r.phi.s, r.dEta=r.dEta, r.dM=r.dM,
                 sphi=res$sphi, sphi.se=res$sphi.se))
}

# ============================================================================
# 6. main() -- CLI entry point (guarded; not run when this file is source()d)
# ============================================================================
usage <- function(){
  cat("Usage: Rscript fit.roc.glm.em.R [--sphi N] [--est-sphi T/F] [--png F]\n",
      "  simulate (default): [--n-genes N] [--sim-sphi N] [--seed N] [--sim-phi-dist gamma|lognormal]\n",
      "  real data:          [--fasta F] [--deta CSV] [--dM CSV] [--phi-ref CSV]\n",
      "  common:             [--lib DIR] [--verbose T/F] [--dry-run] [--help]\n",
      "Default mode SIMULATES a ROC genome and validates recovery vs the known\n",
      "truth; pass --fasta to fit a real genome instead. See the script header.\n", sep="")
}

main <- function(){
  args <- commandArgs(TRUE)
  has.flag <- function(flag) flag %in% args
  getarg <- function(flag, def){
    eqi <- grep(paste0("^", flag, "="), args)
    if (length(eqi)) return(sub(paste0("^", flag, "="), "", args[eqi[1]]))
    i <- match(flag, args)
    if (is.na(i) || i+1 > length(args) || grepl("^--", args[i+1])) return(def)
    args[[i+1]]
  }
  parse_logical <- function(flag, def){
    v <- getarg(flag, def); lv <- tolower(as.character(v))
    if (lv %in% c("t","true","1","yes","y"))  return(TRUE)
    if (lv %in% c("f","false","0","no","n")) return(FALSE)
    stop(sprintf("%s expects a logical (T/F/TRUE/FALSE/1/0/yes/no); got '%s'", flag, v), call.=FALSE)
  }
  parse_num <- function(flag, def){
    v <- getarg(flag, def); n <- suppressWarnings(as.numeric(v))
    if (is.na(n)) stop(sprintf("%s expects a number; got '%s'", flag, v), call.=FALSE)
    n
  }
  if (has.flag("--help") || has.flag("-h")) { usage(); quit(save="no", status=0) }

  lib      <- getarg("--lib", "~/R/lib/main-a664454")
  sphi.fix <- parse_num("--sphi", "1.4")   # canonical fixed-sphi gauge (benchmarks)
  est.sphi <- parse_logical("--est-sphi", "FALSE")
  verbose  <- parse_logical("--verbose", "TRUE")
  dry.run  <- has.flag("--dry-run")
  png.out  <- getarg("--png", "/tmp/roc_glm_em.png")
  ## real-data mode is triggered by --fasta; otherwise simulate (self-contained)
  fasta    <- getarg("--fasta", NA)
  real     <- !is.na(fasta)
  n.genes  <- as.integer(parse_num("--n-genes", "500"))
  sim.sphi <- parse_num("--sim-sphi", "1.4")
  seed     <- as.integer(parse_num("--seed", "1"))
  sim.dist <- getarg("--sim-phi-dist", "gamma")     # 'gamma' (GLMM) or 'lognormal' (native/Stan)

  if (real){
    deta.f  <- getarg("--deta",  NA); dM.f <- getarg("--dM", NA); phi.ref <- getarg("--phi-ref", NA)
    in.files <- c(fasta=fasta, deta=deta.f, dM=dM.f, "phi-ref"=phi.ref)
    if (anyNA(in.files)) stop("real-data mode (--fasta given) requires --deta, --dM and --phi-ref too", call.=FALSE)
    miss <- in.files[!file.exists(path.expand(in.files))]
    if (length(miss)) stop(sprintf("missing input file(s):\n%s",
        paste(sprintf("  --%s : %s", names(miss), miss), collapse="\n")), call.=FALSE)
  }
  if (dry.run){
    cat(sprintf("DRY RUN -- mode=%s  sphi.fix=%g  est.sphi=%s  verbose=%s  png=%s\n",
                if (real) "real" else "simulate", sphi.fix, est.sphi, verbose, png.out))
    if (real) for (nm in names(in.files)) cat(sprintf("  %-8s %s\n", nm, in.files[nm]))
    else cat(sprintf("  simulate: n.genes=%d  sim.sphi=%g  phi.dist=%s  seed=%d\n", n.genes, sim.sphi, sim.dist, seed))
    quit(save="no", status=0)
  }

  .libPaths(c(path.expand(lib), .libPaths()))
  suppressPackageStartupMessages(library(VGAM))

  if (real){
    cat(sprintf("REAL-DATA mode: %s\n", fasta))
    data <- prepare_genome_from_files(fasta, deta.f, dM.f)
    res  <- fit_roc_glm_em(data, sphi.fix, est.sphi, verbose=verbose)
    ref  <- read.csv(phi.ref)
    report_and_plot(res,
      ref.dM     = setNames(data$dMt$Mean, data$dMt$Codon),
      ref.dEta   = setNames(data$det$Mean, data$det$Codon),
      ref.logphi = setNames(ref$log_phi, ref$gene_id),
      ref.sphi.sd= sd(ref$log_phi), ref.label="native ROC fit", png.out=png.out)
  } else {
    cat(sprintf("SIMULATE mode: n.genes=%d  sim.sphi=%g  phi.dist=%s  seed=%d\n",
                n.genes, sim.sphi, sim.dist, seed))
    data <- simulate_roc_genome(n.genes=n.genes, sphi=sim.sphi, seed=seed, phi.dist=sim.dist)
    res  <- fit_roc_glm_em(data, sphi.fix, est.sphi, verbose=verbose)
    tr   <- data$truth
    report_and_plot(res,
      ref.dM     = tr$dM, ref.dEta = tr$dEta,
      ref.logphi = setNames(log(tr$phi), names(tr$phi)),
      ref.sphi.sd= sd(log(tr$phi)), ref.label=sprintf("truth (%s phi)", tr$phi.dist), png.out=png.out)
  }
}

if (sys.nframe() == 0L) main()
