#!/usr/bin/env Rscript
# ============================================================================
# Script:       fit.roc.stan.R
# Version:      0.1.0
# Created:      2026-06-19
# Revised:      2026-06-19
# Purpose:      Fit the ROC codon model by HMC in Stan, using THIS repo's
#               stan/roc_basic.stan, driven from the SAME in-memory data list as
#               the GLM-EM prototype (prototypes/fit.roc.glm.em.R). A clean,
#               self-contained wrapper -- a distilled sibling of the GLM-EM and
#               native fitters for cross-backend comparison.
#
#               roc_basic.stan uses the ENERGY form eta_c = -dM_c - dEta_c*phi_g
#               (reference codon pinned to 0) and a MEAN-gauged lognormal phi
#               prior (log_phi ~ N(-sphi^2/2, sphi), i.e. E[phi]=1). To line the
#               results up with the GLM-EM / simulator convention (log-odds(c/ref)
#               = +dM + dEta*phi, MEDIAN-gauged phi), this wrapper NEGATES the
#               recovered dM/dEta and re-gauges phi to median 1 on extraction.
#
# Provenance:   The cmdstanr-driving + data-prep logic is distilled from the
#               A-RMF analysis pipeline roc/scripts/fit.ROC.stan.R @ ff08d4b
#               (which is YAML/FASTA/AnaCoDa-driven); this wrapper keeps only the
#               roc_basic core and drops the YAML schema / AnaCoDa / lib deps.
#
# Usage:        Rscript fit.roc.stan.R [--sphi N] [--png F]
#                 simulate (default): [--n-genes N] [--sim-sphi N] [--seed N]
#                                     [--sim-phi-dist gamma|lognormal]
#                 stan:               [--chains N] [--threads N] [--warmup N] [--samples N]
#                 common:             [--stan-file F] [--help]
#
# Sourcing:     source()-ing this file defines the functions WITHOUT running the
#               CLI (main() guarded by sys.nframe()==0); it source()s the sibling
#               fit.roc.glm.em.R for the shared simulate_roc_genome / report_and_plot.
#
# Requirements: cmdstanr (+ a built cmdstan); compiles roc_basic.stan with
#               STAN_THREADS so --threads can parallelise the per-gene loop.
#
# AI Model:     Claude Opus 4.8
# Attribution:  Generated by Michael Gilchrist in collaboration with Claude Opus 4.8
# ============================================================================

## locate this script's directory (works run-as-script or sourced) and pull in
## the shared simulator + reporter from the GLM-EM prototype next to it.
.this.file <- sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value=TRUE))
.here <- if (length(.this.file)) dirname(normalizePath(.this.file[1])) else "."
source(file.path(.here, "fit.roc.glm.em.R"))   # simulate_roc_genome, report_and_plot, init_phi_pc1

# ============================================================================
# 1. Build the roc_basic.stan data list from the shared `data` structure
# ============================================================================
## `data` = the list from simulate_roc_genome() / prepare_genome_from_files().
## roc_basic.stan wants the NON-reference codons in a flat K-vector, grouped by
## AA into contiguous [aa_start, aa_end] slices, with y_k = non-ref counts and
## N_ga = per-(gene,AA) totals. Returns the data list + the K-order codon labels.
stan_roc_data <- function(data, sphi, dM.sd=2, dEta.sd=2, grainsize=1){
  CC <- data$CC; AAs <- data$AAs; cba <- data$codons.by.aa; refc <- data$ref.codon
  G <- nrow(CC); A <- length(AAs)
  nonref.by.aa <- lapply(AAs, function(a) setdiff(cba[[a]], refc[a]))  # x-order minus ref
  lens   <- vapply(nonref.by.aa, length, 1L)
  nonref <- unlist(nonref.by.aa, use.names=FALSE)                      # K-vector order
  K <- length(nonref)
  aa_end <- cumsum(lens); aa_start <- aa_end - lens + 1L
  y_k  <- matrix(as.integer(CC[, nonref, drop=FALSE]), G, K)
  N_ga <- vapply(AAs, function(a) rowSums(CC[, cba[[a]], drop=FALSE]), numeric(G))  # G x A
  dat <- list(G=G, A=A, K=K,
              aa_start=as.array(as.integer(aa_start)), aa_end=as.array(as.integer(aa_end)),
              y_k=y_k, N_ga=matrix(as.integer(N_ga), G, A),
              dM_prior_mean=rep(0,K),   dM_prior_sd=rep(dM.sd,K),
              dEta_prior_mean=rep(0,K), dEta_prior_sd=rep(dEta.sd,K),
              sphi=sphi, grainsize=as.integer(grainsize))
  list(dat=dat, nonref=nonref, gid=data$gid, AAs=AAs, codons.by.aa=cba, all.codons=data$all.codons)
}

# ============================================================================
# 2. Fit roc_basic.stan and return results in the GLM-EM `res` shape
# ============================================================================
## Returns the SAME shape as fit_roc_glm_em() so report_and_plot() works directly:
## phi (named by gene, median-gauged), alpha=dM / beta=dEta (named by codon, ref=0,
## in the +(dM+dEta*phi) convention), their posterior-SD SEs, info.th (= 1/Var(log
## phi) from the posterior), sphi, est.sphi=FALSE.
fit_roc_stan <- function(data, sphi.fix=1.0, stan.file=NULL,
                         chains=4, threads=2, warmup=1000, samples=1000, seed=1,
                         dM.sd=2, dEta.sd=2, verbose=TRUE){
  if (!requireNamespace("cmdstanr", quietly=TRUE)) stop("cmdstanr not installed", call.=FALSE)
  if (is.null(stan.file)) stan.file <- normalizePath(file.path(.here, "..", "stan", "roc_basic.stan"))
  if (!file.exists(stan.file)) stop("stan model not found: ", stan.file, call.=FALSE)
  sd <- stan_roc_data(data, sphi.fix, dM.sd=dM.sd, dEta.sd=dEta.sd)
  cat(sprintf("STAN fit: roc_basic.stan  G=%d A=%d K=%d  sphi=%g  chains=%d threads=%d (warmup=%d, samples=%d)\n",
              sd$dat$G, sd$dat$A, sd$dat$K, sphi.fix, chains, threads, warmup, samples))
  mod <- cmdstanr::cmdstan_model(stan.file, cpp_options=list(stan_threads=TRUE))
  ## Anchor every chain in the correct basin: ROC is bimodal (the dEta-sign
  ## mode-flip), so Stan's random init can land in the reverse-mapped mode. Init
  ## log_phi at the data-driven PC1 ranking (the same anchor the GLM-EM uses),
  ## with light per-chain jitter for chain independence.
  phi0 <- init_phi_pc1(data$CC, data$AAs, data$codons.by.aa, data$gid)
  set.seed(seed)
  init_fn <- function() list(log_phi = log(phi0) + rnorm(length(phi0), 0, 0.05),
                             dM   = rnorm(sd$dat$K, 0, 0.1),
                             dEta = rnorm(sd$dat$K, 0, 0.1))
  fit <- mod$sample(data=sd$dat, chains=chains, parallel_chains=chains,
                    threads_per_chain=threads, iter_warmup=warmup, iter_sampling=samples,
                    seed=seed, init=init_fn, refresh=if (verbose) 200 else 0,
                    show_messages=verbose, show_exceptions=FALSE)
  sM <- fit$summary("dM"); sE <- fit$summary("dEta"); sP <- fit$summary("log_phi")
  gid <- sd$gid; all.codons <- sd$all.codons
  alpha <- setNames(numeric(length(all.codons)), all.codons); beta <- alpha
  alpha.se <- setNames(rep(NA_real_, length(all.codons)), all.codons); beta.se <- alpha.se
  alpha[sd$nonref] <- -sM$mean; beta[sd$nonref] <- -sE$mean        # energy-form -> +convention
  alpha.se[sd$nonref] <- sM$sd;  beta.se[sd$nonref] <- sE$sd
  phi <- setNames(exp(sP$mean), gid); phi <- phi/median(phi)        # re-gauge to median 1
  info.th <- setNames(1/sP$sd^2, gid)                              # log-phi posterior precision
  ## convergence headline
  rhat.max <- suppressWarnings(max(c(sM$rhat, sE$rhat, sP$rhat), na.rm=TRUE))
  cat(sprintf("  max Rhat = %.3f  (dM/dEta/log_phi)\n", rhat.max))
  list(phi=phi, alpha=alpha, beta=beta, alpha.se=alpha.se, beta.se=beta.se,
       sphi=sphi.fix, sphi.se=NA, est.sphi=FALSE, info.th=info.th, rhat.max=rhat.max,
       AAs=sd$AAs, codons.by.aa=sd$codons.by.aa, all.codons=all.codons, gid=gid)
}

# ============================================================================
# 3. main() -- CLI entry point (guarded; not run when this file is source()d)
# ============================================================================
usage_stan <- function(){
  cat("Usage: Rscript fit.roc.stan.R [--sphi N] [--png F]\n",
      "  simulate (default): [--n-genes N] [--sim-sphi N] [--seed N] [--sim-phi-dist gamma|lognormal]\n",
      "  stan:               [--chains N] [--threads N] [--warmup N] [--samples N] [--stan-file F]\n",
      "Fits ROC by HMC (stan/roc_basic.stan) on a simulated genome and validates\n",
      "recovery vs the known truth. See the script header.\n", sep="")
}

main_stan <- function(){
  args <- commandArgs(TRUE)
  has.flag <- function(f) f %in% args
  getarg <- function(f, d){ i<-match(f,args); if(is.na(i)||i+1>length(args)||grepl("^--",args[i+1])) d else args[[i+1]] }
  numarg <- function(f, d){ v<-suppressWarnings(as.numeric(getarg(f,d))); if(is.na(v)) stop(f," needs a number",call.=FALSE); v }
  if (has.flag("--help")||has.flag("-h")) { usage_stan(); quit(save="no", status=0) }
  sphi.fix <- numarg("--sphi","1.0"); png.out <- getarg("--png","/tmp/roc_stan.png")
  n.genes <- as.integer(numarg("--n-genes","500")); sim.sphi <- numarg("--sim-sphi","1.0")
  seed <- as.integer(numarg("--seed","1")); sim.dist <- getarg("--sim-phi-dist","gamma")
  chains <- as.integer(numarg("--chains","4")); threads <- as.integer(numarg("--threads","2"))
  warmup <- as.integer(numarg("--warmup","1000")); samples <- as.integer(numarg("--samples","1000"))
  stan.file <- getarg("--stan-file", NA); if (is.na(stan.file)) stan.file <- NULL

  cat(sprintf("SIMULATE mode: n.genes=%d  sim.sphi=%g  phi.dist=%s  seed=%d\n",
              n.genes, sim.sphi, sim.dist, seed))
  data <- simulate_roc_genome(n.genes=n.genes, sphi=sim.sphi, seed=seed, phi.dist=sim.dist)
  res  <- fit_roc_stan(data, sphi.fix, stan.file=stan.file, chains=chains, threads=threads,
                       warmup=warmup, samples=samples, seed=seed)
  tr <- data$truth
  report_and_plot(res, ref.dM=tr$dM, ref.dEta=tr$dEta,
                  ref.logphi=setNames(log(tr$phi), names(tr$phi)),
                  ref.sphi.sd=sd(log(tr$phi)),
                  ref.label=sprintf("truth (%s phi)", tr$phi.dist), png.out=png.out)
}

if (sys.nframe() == 0L) main_stan()
