#!/usr/bin/env Rscript
# ============================================================================
# Script:       fit_roc_glm_em_check.R
# Version:      1.0.0
# Created:      2026-06-19
# Revised:      2026-06-19
# Purpose:      Recovery check for the ROC GLM-EM fitter (prototypes/fit.roc.glm.em.R).
#               Sources that file (functions only -- its main() is guarded), then
#               simulates ROC genomes from KNOWN dM/dEta/phi and verifies the fit
#               recovers them. Run under BOTH phi priors:
#                 - gamma      : matches the GLMM's own prior
#                 - lognormal  : matches native MCMC / Stan
#               so it also demonstrates that recovery is ROBUST to the phi-prior
#               shape mismatch (the codon<->phi multinomial-logit relation is
#               prior-agnostic; the prior only weakly regularises phi).
#
# Usage:        Rscript fit_roc_glm_em_check.R          (run from anywhere)
# Output:       stdout: a recovery table; stops with non-zero status on FAIL.
#
# Requirements: VGAM (same as the fitter).
#
# AI Model:     Claude Opus 4.8
# Attribution:  Generated by Michael Gilchrist in collaboration with Claude Opus 4.8
# ============================================================================

suppressPackageStartupMessages(library(VGAM))

## locate fit.roc.glm.em.R next to this script and source it (main() is guarded
## by sys.nframe()==0, so sourcing only defines the functions)
this.file <- sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value=TRUE))
here <- if (length(this.file)) dirname(normalizePath(this.file)) else "."
source(file.path(here, "fit.roc.glm.em.R"))

## recovery correlations of a single simulate+fit, vs the known truth
recovery <- function(phi.dist, seed, sphi=1.4, n.genes=600, mean.count=15){
  data <- simulate_roc_genome(n.genes=n.genes, sphi=sphi, seed=seed,
                              phi.dist=phi.dist, mean.count=mean.count)
  res  <- fit_roc_glm_em(data, sphi.fix=1.4, est.sphi=FALSE, verbose=FALSE)
  tr <- data$truth
  nz.e <- names(tr$dEta)[abs(tr$dEta) > 1e-12]      # non-reference codons only
  nz.m <- names(tr$dM)[abs(tr$dM) > 1e-12]
  g <- intersect(names(res$phi), names(tr$phi))
  list(phi.spearman = cor(log(res$phi[g]), log(tr$phi[g]), method="spearman"),
       dEta = cor(res$beta[nz.e],  tr$dEta[nz.e]),
       dM   = cor(res$alpha[nz.m], tr$dM[nz.m]))
}

## thresholds: dEta + phi-ranking are recovered tightly; dM (the intercept) is a
## bit softer (and softest under the lognormal prior mismatch), so a lower bar.
TH  <- list(phi.spearman = 0.90, dEta = 0.95, dM = 0.80)
cfg <- expand.grid(phi.dist = c("gamma", "lognormal"), seed = 1:2, stringsAsFactors = FALSE)

cat(sprintf("ROC GLM-EM recovery check (fixed sphi=1.4, n.genes=600)\n%-10s %-4s  %8s %7s %7s   %s\n",
            "phi.dist", "seed", "phi.spS", "dEta", "dM", "result"))
fail <- 0L
for (i in seq_len(nrow(cfg))){
  r  <- recovery(cfg$phi.dist[i], cfg$seed[i])
  ok <- r$phi.spearman >= TH$phi.spearman && abs(r$dEta) >= TH$dEta && abs(r$dM) >= TH$dM
  cat(sprintf("%-10s %-4d  %8.3f %7.3f %7.3f   %s\n",
              cfg$phi.dist[i], cfg$seed[i], r$phi.spearman, r$dEta, r$dM, if (ok) "OK" else "FAIL"))
  if (!ok) fail <- fail + 1L
}

if (fail > 0L)
  stop(sprintf("%d/%d recovery checks FAILED", fail, nrow(cfg)), call. = FALSE)
cat(sprintf("\nALL %d recovery checks PASSED  (phi.spearman>=%.2f, |dEta|>=%.2f, |dM|>=%.2f)\n",
            nrow(cfg), TH$phi.spearman, TH$dEta, TH$dM))
cat("Recovery is robust to the phi-prior shape: the gamma GLMM prior recovers\n",
    "lognormal-simulated phi (native/Stan generative model) about as well.\n", sep="")
