#!/usr/bin/env Rscript
# ============================================================================
# Script:       fit_roc_stan_check.R
# Version:      1.0.0
# Created:      2026-06-19
# Revised:      2026-06-19
# Purpose:      Standalone recovery check for the ROC-on-Stan wrapper
#               (prototypes/fit.roc.stan.R). Simulates a ROC genome from known
#               truth and verifies the Stan fit recovers it -- under BOTH phi
#               priors (gamma / lognormal). Beyond the recovery thresholds, it
#               asserts dEta correlates POSITIVELY with truth (not just |r|): a
#               SIGNED check that the PC1-init kept Stan out of the ROC dEta-sign
#               mode-flip basin and that the energy-form -> +convention negation
#               in the wrapper is correct.
#
# Usage:        Rscript fit_roc_stan_check.R [--n-genes N] [--seed N]
# Output:       stdout: recovery table; stops non-zero on FAIL.
#
# Requirements: cmdstanr + a built cmdstan.
#
# AI Model:     Claude Opus 4.8
# Attribution:  Generated by Michael Gilchrist in collaboration with Claude Opus 4.8
# ============================================================================

suppressPackageStartupMessages(library(VGAM))   # pulled in transitively by the GLM-EM source
this <- sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value=TRUE))
here <- if (length(this)) dirname(normalizePath(this[1])) else "."
source(file.path(here, "fit.roc.stan.R"))        # fit_roc_stan + (via it) simulate_roc_genome

args   <- commandArgs(TRUE)
getarg <- function(f,d){ i<-match(f,args); if(is.na(i)||i+1>length(args)) d else args[[i+1]] }
G    <- as.integer(getarg("--n-genes","300"))
SEED <- as.integer(getarg("--seed","1"))
SPHI <- 1.0

if (!requireNamespace("cmdstanr", quietly=TRUE)) { cat("SKIP: cmdstanr unavailable\n"); quit(save="no", status=0) }

recov <- function(res, tr){
  nz.e <- names(tr$dEta)[abs(tr$dEta) > 1e-12]; nz.m <- names(tr$dM)[abs(tr$dM) > 1e-12]
  g <- intersect(names(res$phi), names(tr$phi))
  c(phi.spS = cor(log(res$phi[g]), log(tr$phi[g]), method="spearman"),
    dEta = cor(res$beta[nz.e], tr$dEta[nz.e]),     # SIGNED: must be positive (correct basin)
    dM   = cor(res$alpha[nz.m], tr$dM[nz.m]),
    rhat = res$rhat.max)
}
## thresholds: dEta SIGNED >= 0.90 (basin + sign), phi rank >= 0.85, |dM| >= 0.75, Rhat <= 1.05
TH <- list(phi.spS=0.85, dEta=0.90, dM=0.75, rhat=1.05)

cat(sprintf("ROC-on-Stan recovery check (G=%d, sphi=%g fixed, seed=%d)\n%-10s %8s %8s %7s %7s   %s\n",
            G, SPHI, SEED, "phi.dist", "phi.spS", "dEta(s)", "dM", "Rhat", "result"))
fail <- 0L
for (dist in c("gamma","lognormal")){
  data <- simulate_roc_genome(n.genes=G, sphi=SPHI, seed=SEED, phi.dist=dist, mean.count=15)
  res  <- fit_roc_stan(data, sphi.fix=SPHI, chains=3, threads=2, warmup=700, samples=700,
                       seed=SEED, verbose=FALSE)
  r  <- recov(res, data$truth)
  ok <- r["phi.spS"]>=TH$phi.spS && r["dEta"]>=TH$dEta && abs(r["dM"])>=TH$dM && r["rhat"]<=TH$rhat
  if (!ok) fail <- fail + 1L
  cat(sprintf("%-10s %8.3f %8.3f %7.3f %7.3f   %s\n", dist, r["phi.spS"], r["dEta"], r["dM"], r["rhat"],
              if (ok) "OK" else "FAIL"))
}
if (fail > 0L) stop(sprintf("%d/2 Stan recovery checks FAILED", fail), call.=FALSE)
cat(sprintf("\nBoth Stan recovery checks PASSED (phi.spS>=%.2f, dEta(signed)>=%.2f, |dM|>=%.2f, Rhat<=%.2f).\n",
            TH$phi.spS, TH$dEta, TH$dM, TH$rhat))
cat("Positive signed dEta confirms the PC1-init avoided the mode-flip and the energy->+convention is correct.\n")
