#!/usr/bin/env Rscript
# ============================================================================
# Script:       native_roc_cell.R
# Version:      1.0.0
# Created:      2026-06-19
# Revised:      2026-06-19
# Purpose:      Native AnaCoDa ROC MCMC cell for the cross-backend recovery
#               comparison. Simulates a ROC genome from known truth (dM,
#               dEta, phi) using AnaCoDa's model$simulateGenome, fits it
#               with native MCMC, then extracts dM/dEta/phi and reports
#               recovery correlations vs. the known truth.
#
#               Truth extraction strategy (A): initializeParameterObject
#               draws random dM/dEta from ROC priors and phi from a
#               lognormal(0, sphi) distribution. The drawn values are
#               extracted BEFORE simulateGenome via:
#                 - parameter$currentMutationParameter  -> dM (list[[1]])
#                 - parameter$currentSelectionParameter -> dEta (list[[1]])
#                 - parameter$getCurrentSynthesisRateForMixture(FALSE) -> phi
#               These are the EXACT values used by simulateGenome, so they
#               are ground truth with no setter calls needed.
#
#               Codon ordering: parameter$getGroupList() returns the 19 AA
#               groups; AAToCodon(aa, TRUE) gives the non-reference codons
#               in the same order as the parameter flat vector.
#
#               Recovery metrics (matched convention):
#                 dM, dEta: Pearson r vs. truth (same sign convention)
#                 phi:      Pearson r on log(phi) + Spearman rho
#
# Usage:        Rscript prototypes/native_roc_cell.R [--seed N] [--samples N]
#                       [--thinning N] [--lib PATH] [--help]
#
#               Or source() and call native_roc_recovery(seed, samples, thinning)
#               directly -- the main() block is guarded by sys.nframe()==0.
#
# Input:        tests/testthat/UnitTestingData/testMCMCROCFiles/
#                 simulatedAllUniqueR.fasta (1000-gene template; used only for
#                 gene lengths -- sequences are replaced by simulateGenome)
#
# Output:       Stdout: convergence log + one-line recovery summary
#               Return: named vector c(phi.spS, dEta, dM)
#
# Requirements:
#   - AnaCoDa installed at ~/R/lib/main-a664454 (or --lib override)
#   - Run with: OMP_NUM_THREADS=1 nice -n 19 Rscript ...
#
# Session:      ROC cross-backend comparison (native cell)
# AI Model:     Claude Sonnet 4.6
# Attribution:  Generated by Michael Gilchrist in collaboration with Claude Sonnet 4.6
# ============================================================================

# ============================================================================
# 0.  Helpers
# ============================================================================

parse_args <- function() {
  args <- commandArgs(trailingOnly = TRUE)
  cfg <- list(
    seed     = 42L,
    samples  = 4000L,
    thinning = 10L,
    lib      = path.expand("~/R/lib/main-a664454"),
    help     = FALSE
  )
  i <- 1L
  while (i <= length(args)) {
    switch(args[i],
      "--seed"     = { cfg$seed     <- as.integer(args[i + 1]); i <- i + 2L },
      "--samples"  = { cfg$samples  <- as.integer(args[i + 1]); i <- i + 2L },
      "--thinning" = { cfg$thinning <- as.integer(args[i + 1]); i <- i + 2L },
      "--lib"      = { cfg$lib      <- args[i + 1];             i <- i + 2L },
      "--help"     = { cfg$help     <- TRUE;                    i <- i + 1L },
      { i <- i + 1L }
    )
  }
  cfg
}

usage <- function() {
  cat("Usage: Rscript prototypes/native_roc_cell.R [OPTIONS]\n")
  cat("  --seed N      RNG seed (default 42)\n")
  cat("  --samples N   MCMC samples after thinning (default 4000)\n")
  cat("  --thinning N  Thinning interval (default 10)\n")
  cat("  --lib PATH    AnaCoDa lib path (default ~/R/lib/main-a664454)\n")
  cat("  --help        Show this message and exit\n")
}

# ============================================================================
# 1.  Core function: simulate -> fit -> compare
# ============================================================================

#' native_roc_recovery
#'
#' Simulate a ROC genome from AnaCoDa-drawn priors, fit with native MCMC,
#' report recovery correlations.
#'
#' @param seed     integer RNG seed for parameter init + MCMC
#' @param samples  number of retained MCMC samples (post-thinning)
#' @param thinning thinning interval; total chain = samples * thinning
#'
#' @return named numeric vector: c(phi.spS, dEta, dM)
#'         phi.spS  = Spearman rho of log(phi_fit) vs log(phi_truth)
#'         dEta     = Pearson r of posterior-mean dEta vs truth dEta
#'         dM       = Pearson r of posterior-mean dM vs truth dM
native_roc_recovery <- function(seed = 42L, samples = 4000L, thinning = 10L) {

  # ---- locate the template FASTA -------------------------------------------
  # Try relative to this script's location first, then from cwd
  script_dir <- tryCatch(
    dirname(normalizePath(sys.frame(0)$ofile, mustWork = TRUE)),
    error = function(e) "."
  )
  repo_root <- normalizePath(file.path(script_dir, ".."), mustWork = FALSE)
  fasta <- file.path(repo_root, "tests", "testthat", "UnitTestingData",
                     "testMCMCROCFiles", "simulatedAllUniqueR.fasta")
  if (!file.exists(fasta)) {
    # fallback: look relative to cwd
    fasta <- file.path("tests", "testthat", "UnitTestingData",
                       "testMCMCROCFiles", "simulatedAllUniqueR.fasta")
  }
  if (!file.exists(fasta)) {
    stop("Cannot find simulatedAllUniqueR.fasta. Run from the repo root or ",
         "set the path explicitly in the script.")
  }
  cat(sprintf("[native_roc_cell] template FASTA: %s\n", fasta))

  # ---- step 1: draw truth parameters via initializeParameterObject ----------
  set.seed(seed)
  genome_template <- initializeGenomeObject(file = fasta)
  n_genes         <- length(genome_template)
  cat(sprintf("[native_roc_cell] template genome: %d genes\n", n_genes))

  sphi_true <- 1.4   # canonical fixed-sphi gauge for critical benchmarks
  parameter_truth <- initializeParameterObject(
    genome          = genome_template,
    sphi            = sphi_true,
    num.mixtures    = 1L,
    gene.assignment = rep(1L, n_genes)
  )

  # Extract truth BEFORE simulateGenome (same values, but safer)
  # Codon ordering: for each AA group, non-reference codons in parameter order
  aa_groups      <- parameter_truth$getGroupList()  # 19 AA groups
  non_ref_codons <- unlist(lapply(aa_groups, function(a) AAToCodon(a, TRUE)))

  dM_truth   <- setNames(unlist(parameter_truth$currentMutationParameter),
                         non_ref_codons)
  dEta_truth <- setNames(unlist(parameter_truth$currentSelectionParameter),
                         non_ref_codons)
  # phi: one value per gene, lognormal with sphi=1
  phi_truth  <- parameter_truth$getCurrentSynthesisRateForMixture(FALSE)

  cat(sprintf("[native_roc_cell] truth dM:   n=%d, range=[%.3f, %.3f]\n",
              length(dM_truth), min(dM_truth), max(dM_truth)))
  cat(sprintf("[native_roc_cell] truth dEta: n=%d, range=[%.3f, %.3f]\n",
              length(dEta_truth), min(dEta_truth), max(dEta_truth)))
  cat(sprintf("[native_roc_cell] truth phi:  n=%d, median=%.3f, range=[%.3f, %.3f]\n",
              length(phi_truth), median(phi_truth), min(phi_truth), max(phi_truth)))

  # ---- step 2: simulate genome from truth parameters -----------------------
  model_truth <- initializeModelObject(parameter_truth, "ROC")
  model_truth$simulateGenome(genome_template)  # modifies genome in-place

  # Write simulated FASTA to a temp file
  sim_fasta <- tempfile(fileext = ".fasta")
  on.exit(unlink(sim_fasta), add = TRUE)
  genome_template$writeFasta(sim_fasta, TRUE)   # TRUE = write simulated seqs
  cat(sprintf("[native_roc_cell] simulated FASTA -> %s\n", sim_fasta))

  # ---- step 3: fit the simulated genome with native MCMC -------------------
  genome_sim <- initializeGenomeObject(file = sim_fasta)
  n_fit      <- length(genome_sim)
  cat(sprintf("[native_roc_cell] fit genome: %d genes\n", n_fit))

  parameter_fit <- initializeParameterObject(
    genome          = genome_sim,
    sphi            = sphi_true,   # reasonable starting point
    num.mixtures    = 1L,
    gene.assignment = rep(1L, n_fit)
  )
  model_fit <- initializeModelObject(parameter_fit, "ROC")

  # Adaptive width: 25-50% of samples is typical; use 50 * thinning
  adaptive_width <- min(50L * thinning, as.integer(samples * 0.25) * thinning)
  adaptive_width <- max(adaptive_width, 10L)

  mcmc_fit <- initializeMCMCObject(
    samples        = samples,
    thinning       = thinning,
    adaptive.width = adaptive_width,
    est.expression = TRUE,
    est.csp        = TRUE,
    est.hyper      = TRUE
  )

  cat(sprintf("[native_roc_cell] starting MCMC: samples=%d thinning=%d adaptive.width=%d\n",
              samples, thinning, adaptive_width))
  cat(sprintf("[native_roc_cell] total chain length: %d iterations\n",
              samples * thinning))
  t_start <- proc.time()["elapsed"]
  runMCMC(mcmc_fit, genome_sim, model_fit, ncores = 1L)
  t_elapsed <- proc.time()["elapsed"] - t_start
  cat(sprintf("[native_roc_cell] MCMC done in %.1f s\n", t_elapsed))

  # ---- step 4: extract posterior means via getCSPEstimates -----------------
  # Use the last 50% of samples as burn-in by default (robust to mild
  # non-convergence in short chains)
  burnin_frac <- 0.5
  keep_samples <- as.integer(samples * (1 - burnin_frac))
  keep_samples <- max(keep_samples, 10L)

  # The TRUTH (currentMutationParameter / currentSelectionParameter) is in the
  # REFERENCE-codon gauge. getCSPEstimates(relative.to.optimal.codon=TRUE) re-
  # references to the OPTIMAL codon per AA -- a different per-AA gauge -- which
  # would artificially depress the dM/dEta correlation. Extract in the matching
  # reference-codon gauge (FALSE); also pull the optimal-codon gauge to confirm
  # the gauge is what matters (a diagnostic, printed below).
  csp_ref <- getCSPEstimates(parameter_fit, samples=keep_samples, mixture=1L,
                             relative.to.optimal.codon = FALSE, report.original.ref = TRUE)
  csp_opt <- getCSPEstimates(parameter_fit, samples=keep_samples, mixture=1L,
                             relative.to.optimal.codon = TRUE,  report.original.ref = TRUE)
  dM_fit   <- setNames(csp_ref$Mutation$Mean,  rownames(csp_ref$Mutation))
  dEta_fit <- setNames(csp_ref$Selection$Mean, rownames(csp_ref$Selection))
  dM_fit_opt   <- setNames(csp_opt$Mutation$Mean,  rownames(csp_opt$Mutation))
  dEta_fit_opt <- setNames(csp_opt$Selection$Mean, rownames(csp_opt$Selection))

  # phi: posterior mean per gene
  phi_fit <- unlist(lapply(seq_len(n_fit), function(gi) {
    parameter_fit$getSynthesisRatePosteriorMeanForGene(keep_samples, gi, FALSE)
  }))

  # ---- step 5: align and compute recovery correlations --------------------
  # Align by codon name (both sets should have identical codons)
  shared_codons <- intersect(names(dM_truth), names(dM_fit))
  if (length(shared_codons) < length(dM_truth)) {
    warning(sprintf("Only %d of %d codons matched between truth and fit",
                    length(shared_codons), length(dM_truth)))
  }

  dM_truth_a   <- dM_truth[shared_codons]
  dM_fit_a     <- dM_fit[shared_codons]
  dEta_truth_a <- dEta_truth[shared_codons]
  dEta_fit_a   <- dEta_fit[shared_codons]

  r_dM   <- cor(dM_truth_a,   dM_fit_a,   method = "pearson")
  r_dEta <- cor(dEta_truth_a, dEta_fit_a, method = "pearson")
  # diagnostic: same metrics under the optimal-codon gauge (expected to be lower
  # if the gauge is the issue rather than convergence)
  r_dM_opt   <- cor(dM_truth_a,   dM_fit_opt[shared_codons],   method = "pearson")
  r_dEta_opt <- cor(dEta_truth_a, dEta_fit_opt[shared_codons], method = "pearson")
  cat(sprintf("[native_roc_cell] GAUGE DIAGNOSTIC: ref-codon  dM=%.4f dEta=%.4f  |  optimal-codon  dM=%.4f dEta=%.4f\n",
              r_dM, r_dEta, r_dM_opt, r_dEta_opt))

  # phi: re-gauge to median=1 for cleaner comparison (removes sphi scale offset)
  phi_truth_g <- phi_truth / median(phi_truth)
  phi_fit_g   <- phi_fit   / median(phi_fit)

  r_phi_pearson  <- cor(log(phi_truth_g), log(phi_fit_g), method = "pearson")
  r_phi_spearman <- cor(phi_truth_g, phi_fit_g, method = "spearman")

  # ---- step 6: report ------------------------------------------------------
  cat(sprintf(
    "[native_roc_cell] RECOVERY: dM=%.4f  dEta=%.4f  phi.Pearson(log)=%.4f  phi.Spearman=%.4f  time=%.1fs\n",
    r_dM, r_dEta, r_phi_pearson, r_phi_spearman, t_elapsed
  ))

  # Sanity check
  if (abs(r_dEta) < 0.9) {
    if (r_dEta < -0.7) {
      cat("[native_roc_cell] NOTE: dEta r is strongly negative -- ROC mode-flip (dEta sign basin).\n")
    } else {
      cat("[native_roc_cell] WARNING: dEta |r| < 0.9 -- chain may not have converged.\n")
    }
  }
  if (r_phi_spearman < 0.85) {
    cat("[native_roc_cell] WARNING: phi Spearman < 0.85 -- chain may not have converged.\n")
  }

  invisible(c(phi.spS = r_phi_spearman, dEta = r_dEta, dM = r_dM))
}

# ============================================================================
# 2.  CLI entry point
# ============================================================================

main <- function() {
  cfg <- parse_args()
  if (cfg$help) { usage(); quit(status = 0L) }

  # Load AnaCoDa
  .libPaths(c(cfg$lib, .libPaths()))
  library(AnaCoDa)

  result <- native_roc_recovery(
    seed     = cfg$seed,
    samples  = cfg$samples,
    thinning = cfg$thinning
  )
  cat(sprintf("\nRECOVERY SUMMARY  phi.Spearman=%.4f  dEta.Pearson=%.4f  dM.Pearson=%.4f\n",
              result["phi.spS"], result["dEta"], result["dM"]))
}

if (sys.nframe() == 0L) main()
