#!/usr/bin/env Rscript
# ============================================================================
# Script:       roc_cross_backend_check.R
# Version:      1.0.0
# Created:      2026-06-19
# Revised:      2026-06-19
# Purpose:      Cross-backend agreement check for the ROC fitters. Simulates ONE
#               genome per phi-prior (gamma = GLMM-style, lognormal = native/Stan
#               style) and fits it with each available backend, verifying that
#               (a) every backend recovers the known truth, and (b) the backends
#               agree WITH EACH OTHER -- despite the Gamma-vs-lognormal phi-prior
#               mismatch (the likelihood is shared; the prior only weakly
#               regularises phi). See notes/sphi-Ne-metrics-gamma-theory.md Sec 9b.
#
#               Backends:
#                 GLMM   prototypes/fit.roc.glm.em.R   (gamma prior; always run)
#                 Stan   prototypes/fit.roc.stan.R     (lognormal prior; needs cmdstanr)
#                 native AnaCoDa ROC MCMC              (lognormal prior; TODO -- the
#                        FASTA/parameter-object path, added separately)
#
# Usage:        Rscript roc_cross_backend_check.R [--n-genes N] [--seed N]
#                                                 [--no-stan]
# Output:       stdout: recovery + agreement table; stops non-zero on FAIL.
#
# Requirements: VGAM (GLMM); cmdstanr + built cmdstan (Stan).
#
# AI Model:     Claude Opus 4.8
# Attribution:  Generated by Michael Gilchrist in collaboration with Claude Opus 4.8
# ============================================================================

suppressPackageStartupMessages(library(VGAM))
this <- sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value=TRUE))
here <- if (length(this)) dirname(normalizePath(this[1])) else "."
source(file.path(here, "fit.roc.glm.em.R"))   # simulate_roc_genome, fit_roc_glm_em, init_phi_pc1
source(file.path(here, "fit.roc.stan.R"))     # fit_roc_stan

args     <- commandArgs(TRUE)
getarg   <- function(f,d){ i<-match(f,args); if(is.na(i)||i+1>length(args)) d else args[[i+1]] }
G        <- as.integer(getarg("--n-genes","400"))
SEED     <- as.integer(getarg("--seed","1"))
SPHI     <- 1.4   # canonical fixed-sphi gauge for critical benchmarks
run.stan <- !("--no-stan" %in% args) && requireNamespace("cmdstanr", quietly=TRUE)

## recovery of a fit vs the known truth (signed; both backends use the
## +(dM+dEta*phi) / median-gauge convention here, so correlations are positive).
recov <- function(res, tr){
  nz.e <- names(tr$dEta)[abs(tr$dEta) > 1e-12]; nz.m <- names(tr$dM)[abs(tr$dM) > 1e-12]
  g <- intersect(names(res$phi), names(tr$phi))
  c(phi.spS = cor(log(res$phi[g]), log(tr$phi[g]), method="spearman"),
    dEta = cor(res$beta[nz.e], tr$dEta[nz.e]),
    dM   = cor(res$alpha[nz.m], tr$dM[nz.m]))
}

TH <- list(phi.spS=0.85, dEta=0.90, dM=0.75, rhat=1.05, agree=0.90)
rows <- list(); fail <- 0L; agree.rows <- list()

for (dist in c("gamma","lognormal")){
  cat(sprintf("\n=== phi.dist = %s ===\n", dist))
  data <- simulate_roc_genome(n.genes=G, sphi=SPHI, seed=SEED, phi.dist=dist, mean.count=15)
  tr <- data$truth
  rg <- fit_roc_glm_em(data, sphi.fix=SPHI, est.sphi=FALSE, verbose=FALSE)
  rows[[paste0("GLMM / ",dist)]] <- c(recov(rg, tr), rhat=NA_real_)
  if (run.stan){
    rs <- fit_roc_stan(data, sphi.fix=SPHI, chains=3, threads=2, warmup=700, samples=700,
                       seed=SEED, verbose=FALSE)
    rows[[paste0("Stan / ",dist)]] <- c(recov(rs, tr), rhat=rs$rhat.max)
    ## backend-vs-backend agreement (not just vs truth): GLMM phi vs Stan phi
    gg <- intersect(names(rg$phi), names(rs$phi))
    agree.rows[[dist]] <- c(phi = cor(log(rg$phi[gg]), log(rs$phi[gg])),
                            dEta = cor(rg$beta[names(tr$dEta)[abs(tr$dEta)>1e-12]],
                                       rs$beta[names(tr$dEta)[abs(tr$dEta)>1e-12]]))
  }
}

cat(sprintf("\nCROSS-BACKEND ROC RECOVERY  (G=%d, sphi=%g fixed, seed=%d)\n", G, SPHI, SEED))
cat(sprintf("%-18s %8s %7s %7s %7s   %s\n","backend / phi","phi.spS","dEta","dM","Rhat","ok"))
for (nm in names(rows)){
  r <- rows[[nm]]
  ok <- r["phi.spS"]>=TH$phi.spS && abs(r["dEta"])>=TH$dEta && abs(r["dM"])>=TH$dM &&
        (is.na(r["rhat"]) || r["rhat"]<=TH$rhat)
  if (!ok) fail <- fail + 1L
  cat(sprintf("%-18s %8.3f %7.3f %7.3f %7s   %s\n", nm, r["phi.spS"], r["dEta"], r["dM"],
              ifelse(is.na(r["rhat"]),"-",sprintf("%.3f",r["rhat"])), ifelse(ok,"OK","FAIL")))
}
if (length(agree.rows)){
  cat("\nBACKEND-vs-BACKEND AGREEMENT (GLMM vs Stan)\n")
  for (dist in names(agree.rows)){
    a <- agree.rows[[dist]]
    ok <- a["phi"]>=TH$agree && abs(a["dEta"])>=TH$agree
    if (!ok) fail <- fail + 1L
    cat(sprintf("  %-10s phi r=%.3f  dEta r=%.3f   %s\n", dist, a["phi"], a["dEta"], ifelse(ok,"OK","FAIL")))
  }
}
if (!run.stan) cat("\n(Stan skipped: cmdstanr unavailable or --no-stan)\n")

if (fail > 0L) stop(sprintf("%d cross-backend check(s) FAILED", fail), call.=FALSE)
cat(sprintf("\nALL cross-backend checks PASSED  (recover truth: phi.spS>=%.2f |dEta|>=%.2f |dM|>=%.2f Rhat<=%.2f;\n",
            TH$phi.spS, TH$dEta, TH$dM, TH$rhat))
cat(sprintf("  backends agree: phi & dEta r>=%.2f). GLMM (gamma prior) and Stan (lognormal prior)\n", TH$agree))
cat("  recover each other's generative model -- cross-backend recovery is robust to the phi-prior shape.\n")
cat("NOTE: native AnaCoDa MCMC recovery is verified separately in native_roc_cell.R\n")
cat("  (dM/dEta ~0.999, phi ~0.98 -- extract in the reference-codon gauge, not optimal-codon).\n")
