# ============================================================================
# File:         scripts/lib/init_helpers.R
# Version:      1.0.0
# Date:         2026-05-21
# Purpose:      Init helpers for Stan ROC fits -- shared between fit.stan.R
#               and tests/test_init_helpers.R.
#
# Exports:      mle_to_init_list, jitter_init, mixture_bootstrap_init
#
# Requirements: none (pure R, no Stan / cmdstanr dependency)
#
# Session:      Adapter MCMC dev (Stan + preflight + tests)
# AI Model:     Claude Opus 4.7
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               ClaudeAI Opus 4.7
# ============================================================================

## Convert a CmdStanMLE $mle() (or $summary()) named vector into a per-parameter
## list (sorted in Stan's natural index order), filtered to the actual
## parameter block (transformed parameters / generated quantities rejected
## by Stan's init).
##
##   mle.df       named numeric vector OR data.frame with $variable/$estimate
##   param.names  character vector of accepted parameter base-names
mle_to_init_list <- function(mle.df, param.names) {
    nm <- names(mle.df)
    base.names <- sub("\\[.*$", "", nm)
    is.param <- base.names %in% param.names
    mle.df <- mle.df[is.param]
    nm <- nm[is.param]
    base.names <- base.names[is.param]
    out <- list()
    for (bn in unique(base.names)) {
        idx <- which(base.names == bn)
        if (length(idx) == 1L && nm[idx] == bn) {
            out[[bn]] <- as.numeric(mle.df[idx])
        } else {
            out[[bn]] <- as.numeric(mle.df[idx][order(nm[idx])])
        }
    }
    out
}

## Per-chain jitter of a single MAP init list.  Without this,
## rep(list(init), chains) seeds all chains at exactly the same point,
## which combined with centered-parameterization funnel curvature in
## sphi-est can leave one chain stuck (E-BFMI < 0.3, rhat > 1.5 on
## log_phi-coupled params -- observed 2026-05-21 on G=1000 sphi-est).
## Per-param-type jitter restores chain diversity without straying from
## the mode's basin.
##
##   log_phi, dM, dEta, mu1, mu2: additive N(0, jitter.sd)
##   sphi, sigma1, sigma2:        multiplicative * exp(N(0, jitter.sd))
##   p:                           logit-space jitter, then back via sigmoid
##
##   init.one     named list of MAP values
##   n.chains     number of chain inits to produce
##   jitter.sd    scalar jitter scale (additive on linear; on log/logit for
##                bounded params)
##   base.seed    seed for reproducibility; chain i uses base.seed*1000 + i
jitter_init <- function(init.one, n.chains, jitter.sd = 0.05, base.seed = 1L) {
    out <- vector("list", n.chains)
    for (i in seq_len(n.chains)) {
        set.seed((base.seed * 1000 + i) %% .Machine$integer.max)
        ji <- init.one
        for (nm in names(ji)) {
            v <- ji[[nm]]
            if (nm %in% c("sphi", "sigma1", "sigma2")) {
                ji[[nm]] <- v * exp(rnorm(length(v), sd = jitter.sd))
            } else if (nm == "p") {
                q  <- log(v / (1 - v))
                qj <- q + rnorm(1L, sd = jitter.sd)
                ji[[nm]] <- 1 / (1 + exp(-qj))
            } else {
                ji[[nm]] <- v + rnorm(length(v), sd = jitter.sd)
            }
        }
        out[[i]] <- ji
    }
    out
}

## SCUO -> log_phi initial values.
##
## Mirrors AnaCoDa's initializeSynthesisRateByGenome path: ranks genes by
## SCUO, maps rank/(G+1) -> quantile of LN(meanlog = -sphi_seed^2/2,
## sdlog = sphi_seed), and returns the corresponding log_phi values.
## High-SCUO genes (strong codon bias, typically high expression) get
## pulled toward the upper quantiles; low-SCUO toward the lower.
##
##   scuo       numeric vector of SCUO values (length G)
##   sphi_seed  positive scalar; the sd of the seed LN distribution
##              (default 1.0 -- a prior-consistent value that does NOT
##               depend on first running a single-LN L-BFGS, which
##               empirically overshrinks sphi at moderate G)
scuo_to_log_phi <- function(scuo, sphi_seed = 1.0) {
    stopifnot(is.numeric(scuo), length(scuo) >= 1L,
              is.numeric(sphi_seed), length(sphi_seed) == 1L, sphi_seed > 0)
    G <- length(scuo)
    r <- rank(scuo, ties.method = "average")
    q <- r / (G + 1L)
    qnorm(q, mean = -0.5 * sphi_seed^2, sd = sphi_seed)
}

## Posterior distribution of Wan-formula SCUO for a single gene.
##
## Treats codon counts within each AA as multinomial draws.  Uses a
## conjugate Dirichlet(alpha) prior on per-AA codon frequencies, samples
## from the Dirichlet posterior, and computes the canonical Wan SCUO
## per posterior draw.  Returns a length-n_draws numeric vector
## quantifying the multinomial sampling uncertainty in the SCUO point
## estimate.
##
##   codon_counts_by_aa  named list; element [[aa]] is a numeric vector
##                       of synonymous codon counts for that AA (length
##                       >= 2; single-codon and stop AAs excluded by
##                       caller).  Composition ratios computed over the
##                       sum of all aa.count values in the list.
##   alpha               Dirichlet prior concentration (default 0.5 =
##                       Jeffreys; use 1 for uniform).
##   n_draws             number of posterior draws (default 2000).
##
## NOTE: caller is responsible for grouping codons by AA in a way that
## matches the model (e.g., AnaCoDa splits Ser into S {TCT,TCC,TCA,TCG}
## and Z {AGT,AGC}).
scuo_posterior <- function(codon_counts_by_aa, alpha = 0.5, n_draws = 2000L) {
    stopifnot(is.list(codon_counts_by_aa), length(codon_counts_by_aa) >= 1L,
              is.numeric(alpha), length(alpha) == 1L, alpha > 0,
              is.numeric(n_draws), length(n_draws) == 1L, n_draws >= 1L)
    n_draws <- as.integer(n_draws)
    aa_counts <- sapply(codon_counts_by_aa, sum)
    total_deg <- sum(aa_counts)
    if (total_deg == 0L) return(rep(NA_real_, n_draws))

    scuo_draws <- numeric(n_draws)
    for (j in seq_along(codon_counts_by_aa)) {
        counts <- codon_counts_by_aa[[j]]
        k <- length(counts)
        if (k < 2L)
            stop("each AA needs >= 2 synonymous codons; got ", k,
                 " for ", names(codon_counts_by_aa)[j], call. = FALSE)
        aaC <- sum(counts)
        if (aaC == 0L) next

        ## Vectorized Dirichlet draws via gamma trick: rgamma reshapes to
        ## an n_draws x k matrix; row-normalize for posterior probabilities.
        shape_vec <- rep(alpha + counts, times = n_draws)
        g <- rgamma(n_draws * k, shape = shape_vec, rate = 1)
        g_mat <- matrix(g, nrow = n_draws, ncol = k, byrow = TRUE)
        p_mat <- g_mat / rowSums(g_mat)

        ## Entropy per draw, treating 0 * log(0) := 0
        log_p <- log(p_mat)
        log_p[!is.finite(log_p)] <- 0
        H_per_draw <- -rowSums(p_mat * log_p)

        Hmax <- log(k)
        O_per_draw <- (Hmax - H_per_draw) / Hmax
        scuo_draws <- scuo_draws + (aaC / total_deg) * O_per_draw
    }
    scuo_draws
}

## Bootstrap a mixture-LN init from a single-LN MAP result.
##   sphi.single     scalar; sphi MAP from the single-LN model
##   single.LN.init  named list with dM, dEta, log_phi (will be carried over)
##   pct_high        initial weight of the high-expression (component 2)
##   percentile      percentile of single-LN phi to target for E[phi | comp 2]
##   sigma2          SD of the narrow component 2
##
## Derives mu1, mu2 to satisfy mean(phi) = 1 across the mixture.  Errors
## (does not return) if (a) numer = 1 - (1-p)*phi.target <= 0, or
## (b) mu2 <= mu1 (label-switching guard).
mixture_bootstrap_init <- function(sphi.single, single.LN.init,
                                   pct_high = 0.05, percentile = 0.99,
                                   sigma2 = 0.3) {
    p      <- 1 - pct_high
    sigma1 <- sphi.single
    ## 99th percentile of phi under single-LN: phi = exp(log_phi),
    ## log_phi ~ N(-sphi^2/2, sphi).  So phi_target = exp(-sphi^2/2 + z*sphi).
    phi.target <- exp(-0.5 * sphi.single^2 + qnorm(percentile) * sphi.single)
    mu2 <- log(phi.target) - 0.5 * sigma2^2
    rhs <- 1 - (1 - p) * phi.target
    if (rhs <= 0)
        stop(sprintf("bootstrap init infeasible: pct_high=%.3f, percentile=%.3f -> phi.target=%.3f, but 1-(1-p)*phi.target=%.3f <= 0.  Reduce pct_high or percentile.",
                     pct_high, percentile, phi.target, rhs), call. = FALSE)
    mu1 <- log(rhs / p) - 0.5 * sigma1^2
    if (mu2 <= mu1)
        stop(sprintf("bootstrap init violates label-switching guard: mu1=%.3f, mu2=%.3f.  Increase percentile or decrease pct_high.",
                     mu1, mu2), call. = FALSE)
    list(
        dM      = single.LN.init$dM,
        dEta    = single.LN.init$dEta,
        log_phi = single.LN.init$log_phi,
        p       = p,
        mu1     = mu1,
        sigma1  = sigma1,
        sigma2  = sigma2
    )
}
