## ============================================================================
## dic.R -- Deviance Information Criterion + helpers
##
## DIC = D_bar + p_D
##   where D(theta) = -2 log L(data | theta)
##   D_bar = E[D(theta)] over posterior   -- from MCMC likelihoodTrace
##   p_D   = effective number of parameters; two estimators:
##
##     p_D_classic = D_bar - D(theta_bar)       (Spiegelhalter et al 2002)
##         requires evaluating L at posterior mean parameters
##
##     p_D_var     = (1/2) var(D(theta))        (Gelman et al 2014)
##         estimable from likelihoodTrace alone; recommended in modern
##         Bayesian practice as more stable + no posterior-mean eval
##
## v1 here computes DIC_var (uses only likelihoodTrace -- works from
## saved mcmc.Rdata without any post-hoc parameter manipulation).
## DIC_classic is provided as a separate function that requires a live
## Parameter + Model + Genome (i.e. called from the R session that ran
## the MCMC; not from post-hoc analysis of saved .Rdata files; see
## ?calculateLogLikelihood on the Model class for the C++-side
## limitation that drives this).
##
## Session:      Lokiarchaeota / Log-likelihood-eval feature
## Date:         2026-05-20
## AI Model:     Claude Opus 4.7
## Attribution:  Generated by Michael Gilchrist in collaboration with
##               ClaudeAI Opus 4.7
## ============================================================================


#' Variance-based DIC (DIC_var, Gelman et al 2014).
#'
#' Uses only the log-likelihood trace from an MCMCAlgorithm object.
#' Works post-hoc from saved mcmc.Rdata without any live Parameter.
#'
#' DIC_var = D_bar + p_D_var
#'   D_bar    = -2 * mean(log L(theta_t))     over posterior samples
#'   p_D_var  = 2 * var(log L(theta_t))       (= (1/2) var(D))
#'
#' @param mcmc           An MCMCAlgorithm Rcpp object (from loadMCMCObject).
#' @param burn.in        Either:
#'                       - numeric in (0, 1): fraction of the trace to drop as burn-in
#'                       - integer >= 1: number of leading samples to drop
#'                       - NULL: drop none (use whole trace)
#'                       Default 0.5 (drop first half).
#' @param min.tail       Minimum number of samples required after burn-in
#'                       (default 100).  Returns NA values if not met.
#'
#' @return A list with elements `D.bar`, `p.D.var`, `DIC.var`, `n.samples`,
#'         `burn.in.used`, `ll.mean`, `ll.var`, and `method = "DIC_var"`.
#'
#' @examples
#' \dontrun{
#' mcmc <- loadMCMCObject("Output/sphi-1/R.Objects/B21_..._round-02_mcmc.Rdata")
#' dic <- dic.var(mcmc, burn.in = 0.5)
#' print(dic)
#' }
#' @export
dic.var <- function(mcmc, burn.in = 0.5, min.tail = 100L) {
    ll <- mcmc$getLogLikelihoodTrace()
    n  <- length(ll)
    drop <- if (is.null(burn.in)) 0L
            else if (burn.in < 1) as.integer(floor(burn.in * n))
            else as.integer(burn.in)
    drop <- max(0L, min(drop, n - min.tail))
    if (n - drop < min.tail) {
        return(list(D.bar = NA_real_, p.D.var = NA_real_, DIC.var = NA_real_,
                    n.samples = n - drop, burn.in.used = drop,
                    method = "DIC_var",
                    note = sprintf("trace too short: %d - %d < %d",
                                   n, drop, min.tail)))
    }
    ll.tail <- ll[(drop + 1):n]
    ll.mean <- mean(ll.tail, na.rm = TRUE)
    ll.var  <- var (ll.tail, na.rm = TRUE)

    D.bar   <- -2 * ll.mean
    p.D.var <-  2 * ll.var
    DIC.var <- D.bar + p.D.var
    list(D.bar       = D.bar,
         p.D.var     = p.D.var,
         DIC.var     = DIC.var,
         n.samples   = length(ll.tail),
         burn.in.used = drop,
         ll.mean     = ll.mean,
         ll.var      = ll.var,
         method      = "DIC_var")
}


#' Set a live Parameter's current state to its posterior mean.
#'
#' Pulls per-gene phi posterior means from the saved trace via
#' \code{parameter$getSynthesisRatePosteriorMeanForGene()} and applies
#' them to the C++ \code{currentSynthesisRateLevel} via the new
#' \code{setCurrentSynthesisRateLevel} bulk setter.  CSP values
#' (currentMutationParameter, currentSelectionParameter) are also
#' replaced with per-codon posterior means via
#' \code{parameter$getCodonSpecificPosteriorMean()} when
#' \code{set.csp = TRUE} (default).
#'
#' This works for a Parameter loaded post-hoc from .Rdata as long as
#' the .Rdata was written by a build that preserves
#' currentSynthesisRateLevel (see \link{writeParameterObject}); the
#' trace data needed by the posterior-mean accessors is already
#' preserved by all builds.
#'
#' Single-mixture only in v1 (\code{numMixtures == 1}).
#'
#' @param parameter   Live Parameter object.
#' @param samples     Number of trailing samples to average for the
#'                    posterior mean (i.e., the post-burn-in tail).
#' @param set.csp     Also replace currentMutationParameter and
#'                    currentSelectionParameter with per-codon posterior
#'                    means (default TRUE).  When FALSE, the loaded
#'                    last-iteration CSP values are kept (a posterior
#'                    draw, but not necessarily the posterior mean).
#' @param mixture     Mixture element to query (1-based; default 1).
#'
#' @return Invisibly returns the modified parameter.
#'
#' @export
setParameterToPosteriorMean <- function(parameter, samples,
                                        set.csp = TRUE, mixture = 1L) {
    stopifnot(is.numeric(samples), length(samples) == 1L,
              samples >= 1L, is.finite(samples))
    samples <- as.integer(samples)

    if (parameter$numMixtures != 1L) {
        stop("setParameterToPosteriorMean: v1 supports numMixtures == 1 only; ",
             "got numMixtures = ", parameter$numMixtures)
    }

    ## --- per-gene phi -----------------------------------------------------
    levels <- parameter$getSynthesisRate()  # vector<vector<double>>
    n.cats <- length(levels)
    if (n.cats == 0L)
        stop("parameter has no currentSynthesisRateLevel categories; ",
             "was it loaded from .Rdata written by an older build?")
    n.genes <- length(levels[[1L]])

    for (cat.i in seq_len(n.cats)) {
        means <- vapply(seq_len(n.genes),
                        function(g) parameter$getSynthesisRatePosteriorMeanForGene(
                                       samples, g, FALSE),
                        FUN.VALUE = double(1L))
        levels[[cat.i]] <- means
    }
    parameter$setCurrentSynthesisRateLevel(levels)

    ## --- per-codon mutation / selection ---------------------------------
    if (set.csp && inherits(parameter, "Rcpp_ROCParameter")) {
        model.conditions <- checkModel(parameter)
        model.uses.ref.codon <- model.conditions$model.uses.ref.codon
        codons <- model.conditions$codons
        if (model.uses.ref.codon) {
            ref.codons <- unlist(lapply(model.conditions$aa, AAToCodon, TRUE))
            codons.nonref <- codons[codons %in% ref.codons]
        } else {
            codons.nonref <- codons
        }

        cur.mut <- parameter$currentMutationParameter
        cur.sel <- parameter$currentSelectionParameter
        for (cat.i in seq_along(cur.mut)) {
            mean.vec.mut <- vapply(codons.nonref, function(co)
                parameter$getCodonSpecificPosteriorMean(
                    mixtureElement = mixture, samples = samples,
                    codon = co, paramType = 0L,
                    withoutReference = model.uses.ref.codon,
                    log_scale = FALSE),
                FUN.VALUE = double(1L))
            mean.vec.sel <- vapply(codons.nonref, function(co)
                parameter$getCodonSpecificPosteriorMean(
                    mixtureElement = mixture, samples = samples,
                    codon = co, paramType = 1L,
                    withoutReference = model.uses.ref.codon,
                    log_scale = FALSE),
                FUN.VALUE = double(1L))
            if (length(mean.vec.mut) == length(cur.mut[[cat.i]]))
                cur.mut[[cat.i]] <- as.numeric(mean.vec.mut)
            if (length(mean.vec.sel) == length(cur.sel[[cat.i]]))
                cur.sel[[cat.i]] <- as.numeric(mean.vec.sel)
        }
        parameter$currentMutationParameter <- cur.mut
        parameter$currentSelectionParameter <- cur.sel
    }

    invisible(parameter)
}


#' Classic DIC (Spiegelhalter et al 2002).
#'
#' Requires evaluating L(data | theta_bar) at the posterior-mean
#' parameter state.  Works on a Parameter loaded post-hoc from
#' .Rdata when the .Rdata was written by a build that preserves
#' currentSynthesisRateLevel (added 2026-05; see
#' \link{writeParameterObject}).  Older .Rdata files require
#' calling this from the R session that ran the MCMC.
#'
#' Two-call workflow:
#' \enumerate{
#'   \item \code{setParameterToPosteriorMean(parameter, samples)} --
#'         replaces current{SynthesisRate,Mutation,Selection} with
#'         posterior means from the trace.
#'   \item \code{dic.classic(parameter, model, genome, mcmc, ...)} --
#'         calls \code{model$calculateLogLikelihood(genome)} at the
#'         posterior-mean state and returns the full DIC list.
#' }
#'
#' This function does NOT call setParameterToPosteriorMean itself
#' because callers may want to evaluate L at points other than the
#' posterior mean (e.g., posterior median, MAP) using the same
#' arithmetic shell.
#'
#' @param parameter   Live Parameter object (with state already set to
#'                    posterior mean by the caller).
#' @param model       Live Model object (parameter must be bound to it).
#' @param genome      Live Genome object (same genes the MCMC saw).
#' @param mcmc        MCMCAlgorithm object with the likelihoodTrace.
#' @param burn.in     Same semantics as dic.var().
#'
#' @return Same list shape as dic.var() but with elements `D.theta.bar`,
#'         `p.D.classic`, `DIC.classic`, and `method = "DIC_classic"`.
#'
#' @export
dic.classic <- function(parameter, model, genome, mcmc,
                        burn.in = 0.5, min.tail = 100L) {
    var.result <- dic.var(mcmc, burn.in = burn.in, min.tail = min.tail)
    if (is.na(var.result$D.bar)) return(var.result)

    ## Caller must have set parameter to posterior mean before calling.
    D.theta.bar <- -2 * model$calculateLogLikelihood(genome)

    p.D.classic <- var.result$D.bar - D.theta.bar
    DIC.classic <- var.result$D.bar + p.D.classic

    list(D.bar       = var.result$D.bar,
         D.theta.bar = D.theta.bar,
         p.D.classic = p.D.classic,
         p.D.var     = var.result$p.D.var,
         DIC.classic = DIC.classic,
         DIC.var     = var.result$DIC.var,
         n.samples   = var.result$n.samples,
         burn.in.used = var.result$burn.in.used,
         ll.mean     = var.result$ll.mean,
         ll.var      = var.result$ll.var,
         method      = "DIC_classic")
}
